<a href="https://colab.research.google.com/github/ever1318-cpu/Apartment_Defect_AI/blob/main/Step02_NOVAPro_%ED%8C%90%EB%B3%84_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 01 — 데이터셋 만들기 (Colab 실행용)

DB에서 하자(defect) 자료를 읽어 메타데이터를 JSON으로 저장합니다.

**출력 파일**
- `dataset_nova.json` — 표본 하자 건 메타데이터 + 사진 URL + 후보 라벨
- `defect_ids_used_nova.json` — 표본 defect_id 목록 (교차검증/재현용)

> ⚠️ 이 노트북은 실서비스 DB에 직접 접속합니다. 비밀번호는 하드코딩하지 않고, 실행할 때마다 안전하게 입력받도록 구성했습니다.

## 1. 패키지 설치

In [59]:
!pip install psycopg2-binary -q

## 2. 라이브러리 임포트

In [60]:
import json
from pathlib import Path
from getpass import getpass

import psycopg2

## 3. DB 접속 정보

비밀번호는 코드에 남기지 않고, 실행 시점에 입력받습니다.
(같은 값을 매번 입력하기 번거로우면 아래 `DB_PASSWORD` 줄의 주석을 풀고 직접 넣어도 됩니다 — 다만 노트북을 공유/저장할 계획이면 권장하지 않습니다.)

In [61]:
DB_HOST = "w-backupdb.c9u0e882q8zp.ap-northeast-2.rds.amazonaws.com"
DB_PORT = 5432
DB_NAME = "BackupDB"
DB_USER = "TruePostgres"

# 실행할 때마다 비밀번호를 입력받습니다 (화면에 노출되지 않음)
#DB_PASSWORD = getpass("DB 비밀번호 입력: ")
DB_PASSWORD = "true2026!!"

DB_CONFIG = {
    "host": DB_HOST,
    "port": DB_PORT,
    "dbname": DB_NAME,
    "user": DB_USER,
    "password": DB_PASSWORD,
}


def get_conn():
    return psycopg2.connect(**DB_CONFIG)

## 4. 추출 설정

In [62]:
#SITE_CODE = "P0256D"  # 울산 다운1차
SITE_CODE = None      # 전체 단지로 확장하려면 None
# SITE_CODE = "P0165D"  # 과천

# 하자 사진 저장 S3
S3_BASE_URL = "https://wmcsm-defect-file.s3.ap-northeast-2.amazonaws.com/"

# --- 사용자 설정: 추출할 데이터 건수 ---
USER_EXTRACTION_COUNT = 2000  # 원하는 추출 수 (예: 100, 1000, 10000)
# -----------------------------------

SAMPLE_LIMIT = USER_EXTRACTION_COUNT
RANDOM_SEED = 0.4207          # 기존 표본과 최대한 겹치도록 동일 seed 유지
MAX_BEFORE_IMAGES = 3

OUT_PATH = Path("dataset_nova.json")
IDS_PATH = Path("defect_ids_used_nova.json")

## 5. 모집단 규모 확인

In [63]:
def count_eligible(cur):
    cur.execute(
        """
        WITH EligibleDefects AS (
            SELECT sd.id
            FROM site_defect sd
            JOIN defect_ho dh ON dh.id = sd.ho_id
            JOIN defect_dong dd ON dd.id = dh.dong_id
            JOIN defect_site ds ON ds.id = dd.site_id
            LEFT JOIN site_defect_file sdf ON sdf.defect_id = sd.id
            WHERE (%(site_code)s IS NULL OR ds.code = %(site_code)s)
              AND sd.type = 'QUALITY'
            GROUP BY sd.id
            HAVING COUNT(sdf.id) FILTER (
                WHERE sdf.full_path IS NOT NULL
                  AND TRIM(sdf.full_path) <> ''
                  AND UPPER(TRIM(sdf.file_type)) = 'BEFORE'
            ) > 0
        )
        SELECT COUNT(id) FROM EligibleDefects
        """,
        {"site_code": SITE_CODE},
    )
    result = cur.fetchone()
    return result[0] if result else 0

## 6. 실/부위/상세부위/공종/하자원인 후보 목록 (계층 매핑)

In [64]:
def load_hierarchy_maps(cur):
    base_from = """
        FROM site_defect sd
        JOIN defect_ho dh ON dh.id = sd.ho_id
        JOIN defect_dong dd ON dd.id = dh.dong_id
        JOIN defect_site ds ON ds.id = dd.site_id
        LEFT JOIN site_site_defect_item di ON di.id = sd.site_defect_item_id
        LEFT JOIN site_site_part_detail_map dm ON dm.id = di.site_site_part_detail_map_id
        LEFT JOIN site_site_area_part_map pm ON pm.id = dm.site_area_part_map_id
        LEFT JOIN defect_area da ON da.id = pm.area_id
        LEFT JOIN defect_part dp ON dp.id = pm.part_id
    """
    base_where = "WHERE (%(site_code)s IS NULL OR ds.code = %(site_code)s) AND sd.type = 'QUALITY'"
    params = {"site_code": SITE_CODE}

    cur.execute(f"SELECT DISTINCT da.name, dp.name {base_from} {base_where}", params)
    area_to_parts = {}
    for area, part in cur.fetchall():
        if area and part:
            area_to_parts.setdefault(area, set()).add(part)

    cur.execute(
        f"""SELECT DISTINCT da.name, dp.name, pdd.name {base_from}
            LEFT JOIN defect_part_detail pdd ON pdd.id = dm.part_detail_id {base_where}""",
        params,
    )
    area_part_to_details = {}
    for area, part, detail in cur.fetchall():
        if area and part and detail:
            area_part_to_details.setdefault((area, part), set()).add(detail)

    cur.execute(
        f"""SELECT DISTINCT da.name, dp.name, wk.name {base_from}
            LEFT JOIN defect_work_kind wk ON wk.id = sd.work_kind_id {base_where}""",
        params,
    )
    area_part_to_workkinds = {}
    for area, part, wk in cur.fetchall():
        if area and part and wk:
            area_part_to_workkinds.setdefault((area, part), set()).add(wk)

    # 하자원인(하자종류)은 실/부위와 직접적인 계층관계가 없는 별도 분류축이므로
    # 위치 기준으로 좁히지 않고 단지 전체 후보를 그대로 준다.
    cur.execute(
        f"""SELECT DISTINCT dc.name
            FROM site_defect sd
            JOIN defect_ho dh ON dh.id = sd.ho_id
            JOIN defect_dong dd ON dd.id = dh.dong_id
            JOIN defect_site ds ON ds.id = dd.site_id
            LEFT JOIN defect_cause dc ON dc.id = sd.cause_id
            {base_where}""",
        params,
    )
    cause_list = sorted(r[0] for r in cur.fetchall() if r[0])

    return {
        "all_areas": sorted(area_to_parts.keys()),
        "area_to_parts": area_to_parts,
        "area_part_to_details": area_part_to_details,
        "area_part_to_workkinds": area_part_to_workkinds,
        "cause_list": cause_list,
    }


def resolve_candidates(defect, maps):
    org_area, org_part, org_detail = defect.get("실"), defect.get("부위"), defect.get("상세부위")

    area_candidates = maps["all_areas"]
    part_candidates = sorted(maps["area_to_parts"].get(org_area, set())) or sorted(
        {p for ps in maps["area_to_parts"].values() for p in ps}
    )
    detail_candidates = sorted(maps["area_part_to_details"].get((org_area, org_part), set()))
    if not detail_candidates and org_detail:
        detail_candidates = [org_detail]
    workkind_candidates = sorted(maps["area_part_to_workkinds"].get((org_area, org_part), set())) or sorted(
        {wk for wks in maps["area_part_to_workkinds"].values() for wk in wks}
    )
    return area_candidates, part_candidates, detail_candidates, workkind_candidates

## 7. 하자 건 + 사진 + 하자원인 포함 조회

In [65]:
def fetch_defects(cur, limit, seed, pool_limit):
    order_expr = "md5(sd.id::text || %(seed_salt)s)" if seed is not None else "random()"
    sql = f"""
        WITH candidate_ids AS (
            SELECT sd.id
            FROM site_defect sd
            JOIN defect_ho dh ON dh.id = sd.ho_id
            JOIN defect_dong dd ON dd.id = dh.dong_id
            JOIN defect_site ds ON ds.id = dd.site_id
            LEFT JOIN site_defect_file sdf ON sdf.defect_id = sd.id
            WHERE (%(site_code)s IS NULL OR ds.code = %(site_code)s)
              AND sd.type = 'QUALITY'
            GROUP BY sd.id
            HAVING COUNT(sdf.id) FILTER (
                WHERE sdf.full_path IS NOT NULL
                  AND TRIM(sdf.full_path) <> ''
                  AND UPPER(TRIM(sdf.file_type)) = 'BEFORE'
            )
            > 0
            ORDER BY {order_expr}
            LIMIT %(pool_limit)s
        )
        SELECT
            sd.id AS defect_id,
            ds.name AS 단지명,
            dd.name AS 동, dh.name AS 호, da.name AS 실,
            dp.name AS 부위, pdd.name AS 상세부위,
            sd.requirement AS 고객민원내용,
            dc.name AS 원본_하자원인,
            wk.name AS 원본_공종,
            json_agg(
                json_build_object(
                    'file_type', sdf.file_type,
                    'full_path', sdf.full_path,
                    'url', %(base_url)s || ltrim(sdf.full_path, '/')
                ) ORDER BY sdf.file_type, sdf.id
            ) FILTER (
                WHERE sdf.full_path IS NOT NULL
                  AND TRIM(sdf.full_path) <> ''
                  AND UPPER(TRIM(sdf.file_type)) = 'BEFORE'
            ) AS 사진목록
        FROM site_defect sd
        JOIN candidate_ids ci ON ci.id = sd.id
        JOIN defect_ho dh ON dh.id = sd.ho_id
        JOIN defect_dong dd ON dd.id = dh.dong_id
        JOIN defect_site ds ON ds.id = dd.site_id
        LEFT JOIN site_site_defect_item di ON di.id = sd.site_defect_item_id
        LEFT JOIN site_site_part_detail_map dm ON dm.id = di.site_site_part_detail_map_id
        LEFT JOIN site_site_area_part_map pm ON pm.id = dm.site_area_part_map_id
        LEFT JOIN defect_area da ON da.id = pm.area_id
        LEFT JOIN defect_part dp ON dp.id = pm.part_id
        LEFT JOIN defect_part_detail pdd ON pdd.id = dm.part_detail_id
        LEFT JOIN defect_cause dc ON dc.id = sd.cause_id
        LEFT JOIN defect_work_kind wk ON wk.id = sd.work_kind_id
        LEFT JOIN site_defect_file sdf ON sdf.defect_id = sd.id
        GROUP BY sd.id, ds.name, dd.name, dh.name, da.name, dp.name, pdd.name,
                 sd.requirement, dc.name, wk.name
        HAVING count(sdf.id) FILTER (
            WHERE sdf.full_path IS NOT NULL
              AND TRIM(sdf.full_path) <> ''
              AND UPPER(TRIM(sdf.file_type)) = 'BEFORE'
        ) > 0
        ORDER BY sd.id
        LIMIT %(limit)s
    """
    params = {
        "base_url": S3_BASE_URL,
        "site_code": SITE_CODE,
        "pool_limit": pool_limit,
        "limit": limit,
    }
    if seed is not None:
        params["seed_salt"] = str(seed)
    cur.execute(sql, params)
    cols = [d[0] for d in cur.description]
    defects = []
    for row in cur.fetchall():
        d = dict(zip(cols, row))
        photos = d.pop("사진목록") or []
        d["photos_before"] = [p for p in photos if p.get("file_type") == "BEFORE"]
        defects.append(d)
    return defects

## 8. 실행 (메인 파이프라인)

In [66]:
def main():
    conn = get_conn()
    cur = conn.cursor()

    total_eligible = count_eligible(cur)
    print(f"모집단(사진 보유 QUALITY 하자, SITE_CODE={SITE_CODE}) 규모: {total_eligible:,}건")
    if total_eligible < SAMPLE_LIMIT:
        print(f"[안내] 모집단이 목표({SAMPLE_LIMIT:,}건)보다 적습니다. 있는 만큼({total_eligible:,}건) 전부 추출합니다.")

    pool_limit = min(SAMPLE_LIMIT * 5, total_eligible) if total_eligible else SAMPLE_LIMIT * 5

    maps = load_hierarchy_maps(cur)
    print(f"후보 목록 로드 완료: 실 {len(maps['all_areas'])}종 / 하자원인 {len(maps['cause_list'])}종")

    defects = fetch_defects(cur, SAMPLE_LIMIT, seed=RANDOM_SEED, pool_limit=pool_limit)
    cur.close()
    conn.close()
    print(f"하자 건 {len(defects)}건 조회 완료 (사진 보유 건 기준)")

    records = []
    skipped_no_photo = 0
    for d in defects:
        photos = [p["url"] for p in d["photos_before"][:MAX_BEFORE_IMAGES]]
        if not photos:
            skipped_no_photo += 1
            continue
        area_c, part_c, detail_c, workkind_c = resolve_candidates(d, maps)
        records.append(
            {
                "defect_id": d["defect_id"],
                "단지명": d["단지명"], "동": d["동"], "호": d["호"],
                "실": d["실"], "부위": d["부위"], "상세부위": d["상세부위"],
                "고객민원내용": d["고객민원내용"],
                "원본_하자원인": d.get("원본_하자원인"),
                "원본_공종": d.get("원본_공종"),
                "photos_before_urls": photos,
                "candidates": {
                    "실": area_c, "부위": part_c, "상세부위": detail_c,
                    "공종": workkind_c, "하자원인": maps["cause_list"],
                },
            }
        )

    OUT_PATH.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")
    IDS_PATH.write_text(json.dumps([r["defect_id"] for r in records], ensure_ascii=False), encoding="utf-8")
    print(f"\n내보내기 완료: {len(records)}건 (사진 없어서 제외: {skipped_no_photo}건)")
    print(f"저장: {OUT_PATH.resolve()}")
    print("저장된 JSON 파일을 이용하여 Nova pro 로 분석 진행하세요")


main()

모집단(사진 보유 QUALITY 하자, SITE_CODE=None) 규모: 151,827건
후보 목록 로드 완료: 실 70종 / 하자원인 11종
하자 건 2000건 조회 완료 (사진 보유 건 기준)

내보내기 완료: 2000건 (사진 없어서 제외: 0건)
저장: /content/dataset_nova.json
저장된 JSON 파일을 이용하여 Nova pro 로 분석 진행하세요

## 9. (선택) 결과를 구글 드라이브에 저장

Colab 세션이 끝나면 로컬 파일이 사라집니다. 결과를 보존하려면 드라이브에 마운트 후 복사하세요.

In [67]:
from google.colab import drive
drive.mount('/content/drive')

import shutil
SAVE_DIR = "/content/drive/MyDrive/dataset_nova_outputs"  # 원하는 경로로 수정
import os
os.makedirs(SAVE_DIR, exist_ok=True)
shutil.copy(OUT_PATH, SAVE_DIR)
shutil.copy(IDS_PATH, SAVE_DIR)
print(f"드라이브에 저장 완료: {SAVE_DIR}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
드라이브에 저장 완료: /content/drive/MyDrive/dataset_nova_outputs

---
# Step 02 (재정의) — AWS Bedrock Nova Pro 판독 · 정답 병기 비교

박태홍님 작성 로직 기준으로 재구성했습니다. 이전 버전과 달라진 점:
- Bearer API 키 대신 **AWS IAM 자격증명(boto3)** 사용 — Colab Secrets 등록 권장
- 실/부위/상세부위/하자원인/공종 5개 항목 판독 + **상세부위는 정확일치·부분일치 둘 다 계산**
- 스로틀링(Throttling) 자동 재시도
- 결과를 `원본_X` / `AI_X` **병기 컬럼**으로 정리 → 엑셀(`NovaPro_분석최종결과.xlsx`)로 저장
- 빈도 상위 N개 클래스만 따로 본 정확도(불균형 클래스 영향 확인용)도 함께 계산

> ⚠️ **보안 주의**: AWS 자격증명은 절대 셀에 하드코딩하지 마세요. Colab 좌측 열쇠 아이콘(🔑) → Secrets에
> `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`(필요시 `AWS_SESSION_TOKEN`)를 등록해두면 자동으로 읽어옵니다.

## 11. 패키지 설치 및 임포트

In [68]:
!pip install -q boto3 openpyxl

In [69]:
import base64
import os
import re
import time
from pathlib import Path

import boto3
import pandas as pd
import requests
from getpass import getpass

## 12. AWS 자격증명 로드
Colab Secrets에 등록돼 있으면 자동으로 읽고, 없으면 안전하게(화면 노출 없이) 직접 입력받습니다.

In [70]:
try:
    from google.colab import userdata
    for k in ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"):
        try:
            v = userdata.get(k)
            if v:
                os.environ[k] = v
        except Exception:
            pass
except ImportError:
    pass

if not os.environ.get("AWS_ACCESS_KEY_ID") or not os.environ.get("AWS_SECRET_ACCESS_KEY"):
    print("Colab Secrets에 등록된 AWS 자격증명이 없어 직접 입력받습니다.")
    os.environ["AWS_ACCESS_KEY_ID"] = getpass("AWS_ACCESS_KEY_ID 입력: ")
    os.environ["AWS_SECRET_ACCESS_KEY"] = getpass("AWS_SECRET_ACCESS_KEY 입력: ")
    _token = getpass("AWS_SESSION_TOKEN (없으면 Enter): ")
    if _token:
        os.environ["AWS_SESSION_TOKEN"] = _token

print("AWS 자격증명 준비 완료")

AWS 자격증명 준비 완료

## 13. 설정값

In [71]:
AWS_REGION = "us-east-1"
NOVA_PRO_MODEL_ID = "us.amazon.nova-pro-v1:0"

# 이번 판독에 쓸 건수 (Step 01에서 만든 dataset_nova.json 전체 중 앞에서부터 N건)
DATA_EXTRACTION_COUNT = 250

DATASET_PATH = Path("/content/dataset_nova.json")
if not DATASET_PATH.exists():
    DATASET_PATH = OUT_PATH  # Step 01에서 정의한 경로 재사용

MAX_BEFORE_IMAGES = 3
REQUEST_DELAY_SEC = 0.3
TOP_N = 5

## 14. 유틸 함수 (일치 판정)

In [72]:
def normalize_text(s):
    return str(s).strip().replace(" ", "")


def exact_match(a, b):
    if not a or not b:
        return None
    na, nb = normalize_text(a), normalize_text(b)
    return None if (not na or not nb) else na == nb


def partial_match(a, b):
    if not a or not b:
        return None
    na, nb = normalize_text(a), normalize_text(b)
    return None if (not na or not nb) else ((na in nb) or (nb in na))


def rate(series):
    valid = series.dropna()
    n = len(valid)
    if n == 0:
        return 0, 0, 0.0
    c = int((valid == True).sum())  # noqa: E712
    return c, n, round(c / n * 100, 1)

## 15. 이미지 다운로드 · 프롬프트 생성

In [73]:
def download_image(url, timeout=20):
    try:
        resp = requests.get(url, timeout=timeout)
        if resp.status_code == 200:
            return resp.content
        print(f"    이미지 HTTP {resp.status_code}: {url}")
    except Exception as e:
        print(f"    이미지 다운로드 실패: {e}")
    return None


def build_prompt(record):
    import json as _json
    c = record["candidates"]
    return f"""아파트 입주 하자 신고 사진(BEFORE)과 민원 내용을 분석하여 아래 JSON 형식으로만 응답하세요. 실/부위/상세부위/하자원인/공종은 오직 사진과 민원 내용만으로 판단하세요.
마크다운이나 설명 문구 없이 JSON 객체 하나만 출력합니다.

[신고 정보]
- 단지: {record['단지명']}  {record['동']}동 {record['호']}호
- 입주민 민원 내용: {record['고객민원내용'] or '(없음)'}

[용어 구분]
- "실"은 공간 구분(거실/안방/욕실/주방/현관 등), "부위"는 그 공간의 표면/구조 구분(벽/바닥/천장/문 등)입니다.
- "하자원인(하자종류)"은 이 하자가 왜 생겼는지의 분류(예: 시공불량/오염/파손 등)이고,
  "공종"은 이 하자를 보수할 담당 공사 종류입니다. 서로 다른 개념이니 혼동하지 마세요.
- 아래 후보 목록 안에서만 선택하고, 목록에 없는 값을 만들어내지 마세요.

[허용 실 목록]
{_json.dumps(c['실'], ensure_ascii=False)}
[허용 부위 목록]
{_json.dumps(c['부위'], ensure_ascii=False)}
[허용 상세부위 목록]
{_json.dumps(c['상세부위'], ensure_ascii=False)}
[허용 하자원인 목록]
{_json.dumps(c['하자원인'], ensure_ascii=False)}
[허용 공종 목록]
{_json.dumps(c['공종'], ensure_ascii=False)}

[반환 JSON 형식]
{{
  "ai_area": "허용 실 목록 중 하나",
  "ai_part": "허용 부위 목록 중 하나",
  "ai_part_detail": "허용 상세부위 목록 중 하나",
  "ai_defect_cause": "허용 하자원인 목록 중 하나",
  "ai_work_kind": "허용 공종 목록 중 하나",
  "confidence": 0.0~1.0,
  "reason": "판단 근거 한 문장"
}}"""

## 16. JSON 파싱 · Nova Pro 호출 (재시도 포함)

In [74]:
def extract_json(raw):
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError:
        pass
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            pass
    return {"ai_area": None, "ai_part": None, "ai_part_detail": None,
            "ai_defect_cause": None, "ai_work_kind": None, "confidence": None,
            "reason": raw[:200], "parse_error": True}


def invoke_nova(bedrock, record):
    content = []
    used = 0
    for url in record["photos_before_urls"][:MAX_BEFORE_IMAGES]:
        img = download_image(url)
        if img is None:
            continue
        content.append({"image": {"format": "jpeg", "source": {"bytes": base64.standard_b64encode(img).decode()}}})
        used += 1
    if used == 0:
        return {"error": "이미지 다운로드 실패"}, "이미지 없음"

    content.append({"text": build_prompt(record)})
    body = json.dumps({"messages": [{"role": "user", "content": content}],
                        "inferenceConfig": {"maxTokens": 500, "temperature": 0}})

    for attempt in range(1, 5):
        try:
            resp = bedrock.invoke_model(modelId=NOVA_PRO_MODEL_ID, body=body)
            raw_body = json.loads(resp["body"].read())
            raw_text = raw_body["output"]["message"]["content"][0]["text"]
            return extract_json(raw_text), None
        except Exception as e:
            if "Throttling" in type(e).__name__ or "TooManyRequests" in str(e):
                wait = 5 * attempt
                print(f"    [스로틀링] {wait}초 대기 후 재시도")
                time.sleep(wait)
                continue
            return None, str(e)
    return None, "재시도 초과"

## 17. 정답 vs Nova Pro 판독결과 병행 비교표

건별로 **실제값(정답)**과 **Nova Pro 예측값**을 항목마다 나란히 놓고, 일치 여부(✓/✗)를 표시합니다.
전체 건을 한눈에 스캔해서 어디서 틀렸는지 바로 확인할 수 있어요.

In [75]:
def compute_row(record, ai, error, model_id):
    org_area, ai_area = record.get("실"), ai.get("ai_area")
    org_part, ai_part = record.get("부위"), ai.get("ai_part")
    org_detail, ai_detail = record.get("상세부위"), ai.get("ai_part_detail")
    org_cause, ai_cause = record.get("원본_하자원인"), ai.get("ai_defect_cause")
    org_work, ai_work = record.get("원본_공종"), ai.get("ai_work_kind")

    if error:
        status = "오류"
    elif ai.get("parse_error"):
        status = "파싱오류"
    elif ai_work is None:
        status = "미분류"
    else:
        status = "성공"

    return {
        "defect_id": record["defect_id"], "동": record["동"], "호": record["호"],
        "원본_실": org_area, "AI_실": ai_area, "실_일치": exact_match(org_area, ai_area),
        "원본_부위": org_part, "AI_부위": ai_part, "부위_일치": exact_match(org_part, ai_part),
        "원본_상세부위": org_detail, "AI_상세부위": ai_detail, "상세부위_일치": exact_match(org_detail, ai_detail),
        "상세부위_부분일치": partial_match(org_detail, ai_detail),
        "원본_하자원인": org_cause, "AI_하자원인": ai_cause, "하자원인_일치": exact_match(org_cause, ai_cause),
        "원본_공종": org_work, "AI_공종": ai_work, "공종_일치": exact_match(org_work, ai_work),
        "AI_신뢰도": ai.get("confidence"), "AI_판단근거": ai.get("reason"),
        "분석상태": status, "model_used": model_id,
    }

## 18. 정확도 요약 함수 (전체 + 빈도 상위 N개 클래스 기준)

In [76]:
def build_accuracy_summary(df, model_name):
    if df.empty:
        return pd.DataFrame([{"항목": "모델", "값": model_name}, {"항목": "전체 시도 건수", "값": 0}])

    ok = df[df["분석상태"] == "성공"]
    fields = [("실", "실_일치"), ("부위", "부위_일치"),
              ("상세부위_정확일치", "상세부위_일치"), ("상세부위_부분일치", "상세부위_부분일치"),
              ("하자원인", "하자원인_일치"), ("공종", "공종_일치")]
    rows = [{"항목": "모델", "값": model_name},
            {"항목": "전체 시도 건수", "값": len(df)},
            {"항목": "성공 건수", "값": len(ok)}, {"항목": "", "값": ""}]
    for label, col in fields:
        c, n, r = rate(ok[col])
        rows.append({"항목": f"[전체] {label} 일치율", "값": f"{c}/{n} = {r}%"})
    rows.append({"항목": "", "값": ""})
    for label, org_col, match_col in [("부위", "원본_부위", "부위_일치"),
                                       ("하자원인", "원본_하자원인", "하자원인_일치"),
                                       ("공종", "원본_공종", "공종_일치")]:
        valid = ok.dropna(subset=[org_col])
        top_classes = valid[org_col].value_counts().head(TOP_N).index.tolist()
        sub = valid[valid[org_col].isin(top_classes)]
        c, n, r = rate(sub[match_col])
        rows.append({"항목": f"[빈도 상위{TOP_N}] {label} 일치율",
                      "값": f"{c}/{n} = {r}% (대상: {', '.join(map(str, top_classes))})"})
    return pd.DataFrame(rows)

## 19. 실행

In [77]:
def main():
    records = json.loads(DATASET_PATH.read_text(encoding="utf-8"))
    records = records[:DATA_EXTRACTION_COUNT]
    print(f"분석 대상 {len(records)}건 로드 ({DATASET_PATH})")

    bedrock = boto3.client(
        "bedrock-runtime", region_name=AWS_REGION,
        aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
        aws_session_token=os.environ.get("AWS_SESSION_TOKEN"),
    )

    rows = []
    t0 = time.time()
    for i, record in enumerate(records, 1):
        current_original_detail = record.get("상세부위", "N/A")
        print(f"[{i:>5}/{len(records)}] defect_id={record['defect_id']} 원본_상세부위={current_original_detail}")

        ai, error = invoke_nova(bedrock, record)
        if error and ai is None:
            ai = {"ai_area": None, "ai_part": None, "ai_part_detail": None,
                  "ai_defect_cause": None, "ai_work_kind": None, "error": error}

        current_ai_detail = ai.get("ai_part_detail", "N/A")
        exact_status = " (정확 일치)" if exact_match(current_original_detail, current_ai_detail) else ""
        partial_status = " (부분 일치)" if partial_match(current_original_detail, current_ai_detail) else ""
        print(f"  -> AI_상세부위={current_ai_detail}{exact_status}{partial_status}")

        rows.append(compute_row(record, ai, error, NOVA_PRO_MODEL_ID))
        time.sleep(REQUEST_DELAY_SEC)

    elapsed = time.time() - t0
    df = pd.DataFrame(rows)
    summary = build_accuracy_summary(df, "AWS Bedrock Nova Pro")

    c_exact, n_exact, r_exact = rate(df["상세부위_일치"])
    print(f"\n[전체 요약] 상세부위_정확일치율: {c_exact}/{n_exact} = {r_exact}%")
    c_partial, n_partial, r_partial = rate(df["상세부위_부분일치"])
    print(f"[전체 요약] 상세부위_부분일치율: {c_partial}/{n_partial} = {r_partial}%")

    out_path = Path("NovaPro_분석최종결과.xlsx")
    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        summary.to_excel(writer, sheet_name="요약", index=False)
        df.to_excel(writer, sheet_name="전체결과", index=False)
    Path("rows_nova_pro.json").write_text(json.dumps(rows, ensure_ascii=False), encoding="utf-8")

    print(f"\n완료: {len(rows)}건, 소요 {elapsed/60:.1f}분")
    print(f"최종 결과: {out_path.resolve()}")
    return df, summary, rows


df, summary, rows = main()

분석 대상 250건 로드 (/content/dataset_nova.json)
[    1/250] defect_id=13052436 원본_상세부위=타일
  -> AI_상세부위=타일 (정확 일치) (부분 일치)
[    2/250] defect_id=13052450 원본_상세부위=코킹
  -> AI_상세부위=타일
[    3/250] defect_id=13052460 원본_상세부위=벽지
  -> AI_상세부위=도장
[    4/250] defect_id=13052509 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[    5/250] defect_id=13052570 원본_상세부위=도장
  -> AI_상세부위=코킹(내장)
[    6/250] defect_id=13052608 원본_상세부위=빨래건조대스위치
  -> AI_상세부위=미분류
[    7/250] defect_id=13052609 원본_상세부위=엔지니어드스톤
  -> AI_상세부위=타일
[    8/250] defect_id=13052638 원본_상세부위=수납장
  -> AI_상세부위=목문
[    9/250] defect_id=13052667 원본_상세부위=걸레받이
  -> AI_상세부위=코킹
[   10/250] defect_id=13052677 원본_상세부위=천정지
  -> AI_상세부위=벽지
[   11/250] defect_id=13052680 원본_상세부위=디딤판
  -> AI_상세부위=코킹
[   12/250] defect_id=13052731 원본_상세부위=걸레받이
  -> AI_상세부위=코킹
[   13/250] defect_id=13052732 원본_상세부위=스프링클러
  -> AI_상세부위=도장
[   14/250] defect_id=13052753 원본_상세부위=벽지
  -> AI_상세부위=도장
[   15/250] defect_id=13052772 원본_상세부위=목문
  -> AI_상세부위=도장
[   16/250] defect_id=13052854 원본_상세부위=타일
  -> AI_상세부위=타일 (정확 일치) (부분 일치)
[   17/250] defect_id=13052894 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   18/250] defect_id=13052925 원본_상세부위=방화문(도장)
  -> AI_상세부위=도어폰
[   19/250] defect_id=13053076 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[   20/250] defect_id=13053092 원본_상세부위=붙박이장
  -> AI_상세부위=코킹
[   21/250] defect_id=13053113 원본_상세부위=천정지
  -> AI_상세부위=벽지
[   22/250] defect_id=13053157 원본_상세부위=목문
  -> AI_상세부위=코킹
[   23/250] defect_id=13053167 원본_상세부위=젠다이인조석
  -> AI_상세부위=타일
[   24/250] defect_id=13053176 원본_상세부위=바탕면(내장)
  -> AI_상세부위=수전
[   25/250] defect_id=13053179 원본_상세부위=벽지
  -> AI_상세부위=미분류
[   26/250] defect_id=13053228 원본_상세부위=벽지
  -> AI_상세부위=도장
[   27/250] defect_id=13053245 원본_상세부위=수납장
  -> AI_상세부위=유리(창호)
[   28/250] defect_id=13053255 원본_상세부위=씽크하부장
  -> AI_상세부위=마루공사
[   29/250] defect_id=13053264 원본_상세부위=씽크하부장
  -> AI_상세부위=None
[   30/250] defect_id=13053286 원본_상세부위=빨래건조대스위치
  -> AI_상세부위=미분류
[   31/250] defect_id=13053313 원본_상세부위=타일
  -> AI_상세부위=타일 (정확 일치) (부분 일치)
[   32/250] defect_id=13053328 원본_상세부위=걸레받이
  -> AI_상세부위=바탕면
[   33/250] defect_id=13053331 원본_상세부위=목문
  -> AI_상세부위=전등스위치
[   34/250] defect_id=13053356 원본_상세부위=천정지
  -> AI_상세부위=천정면(내장)
[   35/250] defect_id=13053399 원본_상세부위=목문
  -> AI_상세부위=목문 (정확 일치) (부분 일치)
[   36/250] defect_id=13053403 원본_상세부위=수전
  -> AI_상세부위=수전 (정확 일치) (부분 일치)
[   37/250] defect_id=13053462 원본_상세부위=도장
  -> AI_상세부위=수전
[   38/250] defect_id=13053493 원본_상세부위=젠다이인조석
  -> AI_상세부위=거울
[   39/250] defect_id=13053497 원본_상세부위=바탕면(내장)
  -> AI_상세부위=코킹(창호)
[   40/250] defect_id=13053500 원본_상세부위=목문
  -> AI_상세부위=창호
[   41/250] defect_id=13053501 원본_상세부위=벽지
  -> AI_상세부위=도장
[   42/250] defect_id=13053506 원본_상세부위=목문
  -> AI_상세부위=문틀
[   43/250] defect_id=13053512 원본_상세부위=젠다이인조석
  -> AI_상세부위=None
[   44/250] defect_id=13053524 원본_상세부위=벽지
  -> AI_상세부위=AL창
[   45/250] defect_id=13053526 원본_상세부위=걸레받이
  -> AI_상세부위=미분류
[   46/250] defect_id=13053544 원본_상세부위=천정지
  -> AI_상세부위=바탕면
[   47/250] defect_id=13053566 원본_상세부위=중문(레일)
  -> AI_상세부위=코킹
[   48/250] defect_id=13053612 원본_상세부위=천정지
  -> AI_상세부위=천정지 (정확 일치) (부분 일치)
[   49/250] defect_id=13053624 원본_상세부위=화장대
  -> AI_상세부위=바닥
[   50/250] defect_id=13053644 원본_상세부위=준공청소
  -> AI_상세부위=코킹
[   51/250] defect_id=13053654 원본_상세부위=유리(창호)
  -> AI_상세부위=유리(창호) (정확 일치) (부분 일치)
[   52/250] defect_id=13053677 원본_상세부위=벽지
  -> AI_상세부위=미분류
[   53/250] defect_id=13053707 원본_상세부위=몰딩
  -> AI_상세부위=코킹(가구)
[   54/250] defect_id=13053741 원본_상세부위=바탕면(내장)
  -> AI_상세부위=도장
[   55/250] defect_id=13053754 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   56/250] defect_id=13053767 원본_상세부위=바탕면(내장)
  -> AI_상세부위=수전
[   57/250] defect_id=13053778 원본_상세부위=강마루84
  -> AI_상세부위=바탕면(미장)
[   58/250] defect_id=13053812 원본_상세부위=도장
  -> AI_상세부위=코킹(창호)
[   59/250] defect_id=13053813 원본_상세부위=벽지
  -> AI_상세부위=코킹
[   60/250] defect_id=13053832 원본_상세부위=걸레받이
  -> AI_상세부위=바닥
[   61/250] defect_id=13053847 원본_상세부위=도장
  -> AI_상세부위=코킹
[   62/250] defect_id=13053869 원본_상세부위=씽크상부장
  -> AI_상세부위=도장
[   63/250] defect_id=13053879 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   64/250] defect_id=13053935 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   65/250] defect_id=13053937 원본_상세부위=환기구(캡)
  -> AI_상세부위=목문
[   66/250] defect_id=13053991 원본_상세부위=젠다이인조석
  -> AI_상세부위=타일
[   67/250] defect_id=13053994 원본_상세부위=코킹(타일)
  -> AI_상세부위=타일 (부분 일치)
[   68/250] defect_id=13054002 원본_상세부위=씽크상부장
  -> AI_상세부위=도장
[   69/250] defect_id=13054012 원본_상세부위=수납장
  -> AI_상세부위=몰딩
[   70/250] defect_id=13054050 원본_상세부위=걸레받이(대리석)
  -> AI_상세부위=코킹
[   71/250] defect_id=13054077 원본_상세부위=붙박이장
  -> AI_상세부위=코킹
[   72/250] defect_id=13054083 원본_상세부위=벽지
  -> AI_상세부위=도장
[   73/250] defect_id=13054097 원본_상세부위=걸레받이
  -> AI_상세부위=바닥
[   74/250] defect_id=13054107 원본_상세부위=변기
  -> AI_상세부위=변기 (정확 일치) (부분 일치)
[   75/250] defect_id=13054130 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   76/250] defect_id=13054138 원본_상세부위=PL창
  -> AI_상세부위=AL창
[   77/250] defect_id=13054186 원본_상세부위=걸레받이
  -> AI_상세부위=바닥
[   78/250] defect_id=13054187 원본_상세부위=도장
  -> AI_상세부위=코킹
[   79/250] defect_id=13054197 원본_상세부위=수납장
  -> AI_상세부위=도장
[   80/250] defect_id=13054202 원본_상세부위=PL창
  -> AI_상세부위=PL창(코킹) (부분 일치)
[   81/250] defect_id=13054208 원본_상세부위=에폭시
  -> AI_상세부위=코킹
[   82/250] defect_id=13054209 원본_상세부위=도장
  -> AI_상세부위=코킹(내장)
[   83/250] defect_id=13054210 원본_상세부위=몰딩
  -> AI_상세부위=천정지
[   84/250] defect_id=13054214 원본_상세부위=바탕면(내장)
  -> AI_상세부위=수전
[   85/250] defect_id=13054238 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[   86/250] defect_id=13054249 원본_상세부위=코킹
  -> AI_상세부위=미분류
[   87/250] defect_id=13054255 원본_상세부위=수납장
  -> AI_상세부위=코킹
[   88/250] defect_id=13054269 원본_상세부위=냉장고장
  -> AI_상세부위=전기콘센트
[   89/250] defect_id=13054272 원본_상세부위=코킹
  -> AI_상세부위=코킹 (정확 일치) (부분 일치)
[   90/250] defect_id=13054291 원본_상세부위=천정지
  -> AI_상세부위=몰딩
[   91/250] defect_id=13054292 원본_상세부위=도장
  -> AI_상세부위=코킹(창호)
[   92/250] defect_id=13054332 원본_상세부위=PL창
  -> AI_상세부위=유리
[   93/250] defect_id=13054337 원본_상세부위=벽지
  -> AI_상세부위=도장
[   94/250] defect_id=13054376 원본_상세부위=에폭시
  -> AI_상세부위=바탕면(미장)
[   95/250] defect_id=13054425 원본_상세부위=벽지
  -> AI_상세부위=도장
[   96/250] defect_id=13054442 원본_상세부위=도장
  -> AI_상세부위=미분류
[   97/250] defect_id=13054454 원본_상세부위=천정지
  -> AI_상세부위=천정지 (정확 일치) (부분 일치)
[   98/250] defect_id=13054465 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[   99/250] defect_id=13054480 원본_상세부위=준공청소
  -> AI_상세부위=코킹
[  100/250] defect_id=13054482 원본_상세부위=벽지
  -> AI_상세부위=도장
[  101/250] defect_id=13054491 원본_상세부위=단열보드
  -> AI_상세부위=수전
[  102/250] defect_id=13054515 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[  103/250] defect_id=13054531 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=도장 (부분 일치)
[  104/250] defect_id=13054533 원본_상세부위=도장
  -> AI_상세부위=바탕면
[  105/250] defect_id=13054566 원본_상세부위=준공청소
  -> AI_상세부위=도장
[  106/250] defect_id=13054572 원본_상세부위=도장
  -> AI_상세부위=수전
[  107/250] defect_id=13054575 원본_상세부위=붙박이장
  -> AI_상세부위=붙박이장 (정확 일치) (부분 일치)
[  108/250] defect_id=13054578 원본_상세부위=천정지
  -> AI_상세부위=몰딩
[  109/250] defect_id=13054590 원본_상세부위=벽지
  -> AI_상세부위=전기콘센트
[  110/250] defect_id=13054612 원본_상세부위=몰딩
  -> AI_상세부위=천정면(내장)
[  111/250] defect_id=13054646 원본_상세부위=씽크상부장
  -> AI_상세부위=코킹
[  112/250] defect_id=13054652 원본_상세부위=천정지
  -> AI_상세부위=도장
[  113/250] defect_id=13054707 원본_상세부위=PL창
  -> AI_상세부위=발코니난간
[  114/250] defect_id=13054712 원본_상세부위=도장
  -> AI_상세부위=수전
[  115/250] defect_id=13054736 원본_상세부위=천정지
  -> AI_상세부위=도장
[  116/250] defect_id=13054746 원본_상세부위=붙박이장
  -> AI_상세부위=코킹
[  117/250] defect_id=13054767 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[  118/250] defect_id=13054772 원본_상세부위=천정지
  -> AI_상세부위=몰딩
[  119/250] defect_id=13054817 원본_상세부위=몰딩
  -> AI_상세부위=None
[  120/250] defect_id=13054820 원본_상세부위=씽크하부장
  -> AI_상세부위=도장
[  121/250] defect_id=13054858 원본_상세부위=도장
  -> AI_상세부위=코킹(창호)
[  122/250] defect_id=13054883 원본_상세부위=변기
  -> AI_상세부위=타일
[  123/250] defect_id=13054942 원본_상세부위=단열보드
  -> AI_상세부위=환기구(캡)
[  124/250] defect_id=13054969 원본_상세부위=코킹
  -> AI_상세부위=코킹 (정확 일치) (부분 일치)
[  125/250] defect_id=13054971 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  126/250] defect_id=13054998 원본_상세부위=벽지
  -> AI_상세부위=코킹
[  127/250] defect_id=13055045 원본_상세부위=PL창
  -> AI_상세부위=코킹(창호)
[  128/250] defect_id=13055101 원본_상세부위=코킹(유리)
  -> AI_상세부위=코킹 (부분 일치)
[  129/250] defect_id=13055111 원본_상세부위=천정지
  -> AI_상세부위=천정지 (정확 일치) (부분 일치)
[  130/250] defect_id=13055113 원본_상세부위=신발장
  -> AI_상세부위=도장
[  131/250] defect_id=13055133 원본_상세부위=펜트리문
  -> AI_상세부위=코킹
[  132/250] defect_id=13055138 원본_상세부위=벽지
  -> AI_상세부위=미분류
[  133/250] defect_id=13055143 원본_상세부위=신발장
  -> AI_상세부위=코킹
[  134/250] defect_id=13055150 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=바탕면
[  135/250] defect_id=13055171 원본_상세부위=벽지
  -> AI_상세부위=미분류
[  136/250] defect_id=13055180 원본_상세부위=벽지
  -> AI_상세부위=미분류
[  137/250] defect_id=13055206 원본_상세부위=씽크상부장
  -> AI_상세부위=렌지후드
[  138/250] defect_id=13055221 원본_상세부위=도장
  -> AI_상세부위=코킹
[  139/250] defect_id=13055233 원본_상세부위=도장
  -> AI_상세부위=수전
[  140/250] defect_id=13055298 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  141/250] defect_id=13055301 원본_상세부위=천정지
  -> AI_상세부위=코킹
[  142/250] defect_id=13055311 원본_상세부위=천정지
  -> AI_상세부위=미분류
[  143/250] defect_id=13055333 원본_상세부위=PL창
  -> AI_상세부위=문틀
[  144/250] defect_id=13055335 원본_상세부위=벽지
  -> AI_상세부위=바탕면
[  145/250] defect_id=13055341 원본_상세부위=천정지
  -> AI_상세부위=천정면(내장)
[  146/250] defect_id=13055350 원본_상세부위=도장
  -> AI_상세부위=미분류
[  147/250] defect_id=13055358 원본_상세부위=아일랜드식탁장
  -> AI_상세부위=코킹
[  148/250] defect_id=13055363 원본_상세부위=도장
  -> AI_상세부위=코킹
[  149/250] defect_id=13055384 원본_상세부위=벽지
  -> AI_상세부위=도장
[  150/250] defect_id=13055406 원본_상세부위=도장
  -> AI_상세부위=바탕면(미장)
[  151/250] defect_id=13055450 원본_상세부위=도장(외부)
  -> AI_상세부위=발코니난간
[  152/250] defect_id=13055469 원본_상세부위=벽지
  -> AI_상세부위=코킹
[  153/250] defect_id=13055476 원본_상세부위=PL창
  -> AI_상세부위=코킹(창호)
[  154/250] defect_id=13055483 원본_상세부위=수납장
  -> AI_상세부위=도장
[  155/250] defect_id=13055496 원본_상세부위=벽지
  -> AI_상세부위=코킹
[  156/250] defect_id=13055504 원본_상세부위=도장
  -> AI_상세부위=코킹
[  157/250] defect_id=13055534 원본_상세부위=수납장
  -> AI_상세부위=타일
[  158/250] defect_id=13055537 원본_상세부위=PL창
  -> AI_상세부위=PL창 (정확 일치) (부분 일치)
[  159/250] defect_id=13055554 원본_상세부위=씽크상부장
  -> AI_상세부위=PD점검함(잡철)
[  160/250] defect_id=13055562 원본_상세부위=화장대
  -> AI_상세부위=코킹
[  161/250] defect_id=13055575 원본_상세부위=씽크상부장
  -> AI_상세부위=미분류
[  162/250] defect_id=13055585 원본_상세부위=씽크하부장
  -> AI_상세부위=코킹(대리석)
[  163/250] defect_id=13055603 원본_상세부위=벽지
  -> AI_상세부위=창대석
[  164/250] defect_id=13055619 원본_상세부위=세면대상판(인조)
  -> AI_상세부위=욕실천정재일반
[  165/250] defect_id=13055662 원본_상세부위=펜트리문
  -> AI_상세부위=바탕면
[  166/250] defect_id=13055683 원본_상세부위=천정지
  -> AI_상세부위=몰딩
[  167/250] defect_id=13055684 원본_상세부위=수납장
  -> AI_상세부위=미분류
[  168/250] defect_id=13055687 원본_상세부위=벽지
  -> AI_상세부위=코킹
[  169/250] defect_id=13055705 원본_상세부위=도장
  -> AI_상세부위=코킹
[  170/250] defect_id=13055724 원본_상세부위=천정지
  -> AI_상세부위=천정면(내장)
[  171/250] defect_id=13055732 원본_상세부위=붙박이장
  -> AI_상세부위=코킹
[  172/250] defect_id=13055752 원본_상세부위=화장대상판(인조)
  -> AI_상세부위=AL창
[  173/250] defect_id=13055772 원본_상세부위=목문
  -> AI_상세부위=문틀
[  174/250] defect_id=13055817 원본_상세부위=강마루84
  -> AI_상세부위=도장
[  175/250] defect_id=13055826 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  176/250] defect_id=13055831 원본_상세부위=도장
  -> AI_상세부위=코킹
[  177/250] defect_id=13055833 원본_상세부위=벽지
  -> AI_상세부위=미분류
[  178/250] defect_id=13055837 원본_상세부위=바탕면(내장)
  -> AI_상세부위=전기콘센트
[  179/250] defect_id=13055839 원본_상세부위=벽지
  -> AI_상세부위=도장
[  180/250] defect_id=13055855 원본_상세부위=씽크상부장
  -> AI_상세부위=엔지니어드스톤
[  181/250] defect_id=13055868 원본_상세부위=벽지
  -> AI_상세부위=도장
[  182/250] defect_id=13055891 원본_상세부위=씽크상부장
  -> AI_상세부위=코킹
[  183/250] defect_id=13055916 원본_상세부위=천정면(내장)
  -> AI_상세부위=천정면(내장) (정확 일치) (부분 일치)
[  184/250] defect_id=13055927 원본_상세부위=준공청소
  -> AI_상세부위=코킹(창호)
[  185/250] defect_id=13055937 원본_상세부위=바탕면(내장)
  -> AI_상세부위=코킹
[  186/250] defect_id=13055947 원본_상세부위=걸레받이
  -> AI_상세부위=미분류
[  187/250] defect_id=13055962 원본_상세부위=욕실장
  -> AI_상세부위=타일
[  188/250] defect_id=13055966 원본_상세부위=에폭시
  -> AI_상세부위=바탕면(미장)
[  189/250] defect_id=13056012 원본_상세부위=천정지
  -> AI_상세부위=미분류
[  190/250] defect_id=13056025 원본_상세부위=씽크상부장
  -> AI_상세부위=도장
[  191/250] defect_id=13056064 원본_상세부위=PL창
  -> AI_상세부위=코킹(창호)
[  192/250] defect_id=13056123 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  193/250] defect_id=13056138 원본_상세부위=천정지
  -> AI_상세부위=몰딩
[  194/250] defect_id=13056230 원본_상세부위=도장
  -> AI_상세부위=코킹(내장)
[  195/250] defect_id=13056242 원본_상세부위=중문(레일)
  -> AI_상세부위=코킹
[  196/250] defect_id=13056274 원본_상세부위=천정지
  -> AI_상세부위=벽지
[  197/250] defect_id=13056300 원본_상세부위=도어록목문
  -> AI_상세부위=코킹
[  198/250] defect_id=13056304 원본_상세부위=바탕면(내장)
  -> AI_상세부위=코킹(창호)
[  199/250] defect_id=13056380 원본_상세부위=바탕면(내장)
  -> AI_상세부위=코킹(창호)
[  200/250] defect_id=13056385 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  201/250] defect_id=13056435 원본_상세부위=PL창
  -> AI_상세부위=코킹
[  202/250] defect_id=13056456 원본_상세부위=붙박이장
  -> AI_상세부위=미분류
[  203/250] defect_id=13056457 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=도장 (부분 일치)
[  204/250] defect_id=13056477 원본_상세부위=아일랜드식탁장
  -> AI_상세부위=타일
[  205/250] defect_id=13056487 원본_상세부위=벽지
  -> AI_상세부위=None
[  206/250] defect_id=13056493 원본_상세부위=붙박이장
  -> AI_상세부위=목문
[  207/250] defect_id=13056496 원본_상세부위=단열보드
  -> AI_상세부위=수전
[  208/250] defect_id=13056497 원본_상세부위=신발장
  -> AI_상세부위=거울
[  209/250] defect_id=13056506 원본_상세부위=목문
  -> AI_상세부위=환기구(캡)
[  210/250] defect_id=13056513 원본_상세부위=걸레받이
  -> AI_상세부위=코킹
[  211/250] defect_id=13056550 원본_상세부위=천정지
  -> AI_상세부위=벽지
[  212/250] defect_id=13056554 원본_상세부위=전등스위치
  -> AI_상세부위=전기콘센트
[  213/250] defect_id=13056586 원본_상세부위=벽지
  -> AI_상세부위=바탕면
[  214/250] defect_id=13056587 원본_상세부위=PL창
  -> AI_상세부위=None
[  215/250] defect_id=13056616 원본_상세부위=전등스위치
  -> AI_상세부위=전기콘센트
[  216/250] defect_id=13056631 원본_상세부위=바탕면(내장)
  -> AI_상세부위=None
[  217/250] defect_id=13056636 원본_상세부위=PL창
  -> AI_상세부위=코킹(창호)
[  218/250] defect_id=13056646 원본_상세부위=도장
  -> AI_상세부위=설비입상배관
[  219/250] defect_id=13056666 원본_상세부위=붙박이장
  -> AI_상세부위=도장
[  220/250] defect_id=13056681 원본_상세부위=바탕면(내장)
  -> AI_상세부위=전기콘센트
[  221/250] defect_id=13056687 원본_상세부위=도장
  -> AI_상세부위=바탕면(미장)
[  222/250] defect_id=13056727 원본_상세부위=벽지
  -> AI_상세부위=도장
[  223/250] defect_id=13056731 원본_상세부위=PL창틀(코킹)
  -> AI_상세부위=코킹(창호)
[  224/250] defect_id=13056734 원본_상세부위=강마루84
  -> AI_상세부위=코킹(마루)
[  225/250] defect_id=13056777 원본_상세부위=목문
  -> AI_상세부위=도장
[  226/250] defect_id=13056779 원본_상세부위=벽지
  -> AI_상세부위=도장
[  227/250] defect_id=13056782 원본_상세부위=PL창
  -> AI_상세부위=유리(창호)
[  228/250] defect_id=13056809 원본_상세부위=천정지
  -> AI_상세부위=도장
[  229/250] defect_id=13056810 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[  230/250] defect_id=13056858 원본_상세부위=걸레받이
  -> AI_상세부위=코킹
[  231/250] defect_id=13056859 원본_상세부위=수납장
  -> AI_상세부위=미분류
[  232/250] defect_id=13056870 원본_상세부위=엔지니어드스톤
  -> AI_상세부위=타일
[  233/250] defect_id=13056904 원본_상세부위=PL창
  -> AI_상세부위=발코니난간
[  234/250] defect_id=13056909 원본_상세부위=씽크하부장
  -> AI_상세부위=미분류
[  235/250] defect_id=13056956 원본_상세부위=PL창
  -> AI_상세부위=코킹
[  236/250] defect_id=13056957 원본_상세부위=벽지
  -> AI_상세부위=미분류
[  237/250] defect_id=13056961 원본_상세부위=도장
  -> AI_상세부위=화재감지기
[  238/250] defect_id=13056979 원본_상세부위=도장
  -> AI_상세부위=수전
[  239/250] defect_id=13056990 원본_상세부위=걸레받이
  -> AI_상세부위=None
[  240/250] defect_id=13056996 원본_상세부위=코킹(욕조)
  -> AI_상세부위=코킹 (부분 일치)
[  241/250] defect_id=13057021 원본_상세부위=천정지
  -> AI_상세부위=천정면(내장)
[  242/250] defect_id=13057052 원본_상세부위=에폭시
  -> AI_상세부위=바탕면(미장)
[  243/250] defect_id=13057072 원본_상세부위=도장
  -> AI_상세부위=도장 (정확 일치) (부분 일치)
[  244/250] defect_id=13057078 원본_상세부위=방화문
  -> AI_상세부위=도장
[  245/250] defect_id=13057086 원본_상세부위=벽지
  -> AI_상세부위=도장
[  246/250] defect_id=13057089 원본_상세부위=도장
  -> AI_상세부위=수전
[  247/250] defect_id=13057093 원본_상세부위=바탕면(내장)
  -> AI_상세부위=수전
[  248/250] defect_id=13057109 원본_상세부위=붙박이장
  -> AI_상세부위=도장
[  249/250] defect_id=13057110 원본_상세부위=방화문틀(도장)
  -> AI_상세부위=코킹
[  250/250] defect_id=13057112 원본_상세부위=중문(레일)
  -> AI_상세부위=코킹

[전체 요약] 상세부위_정확일치율: 28/243 = 11.5%
[전체 요약] 상세부위_부분일치율: 34/243 = 14.0%

완료: 250건, 소요 22.5분
최종 결과: /content/NovaPro_분석최종결과.xlsx

## 20. 정확도 요약 표

In [78]:
summary

                    항목                                                     값
0                   모델                                  AWS Bedrock Nova Pro
1             전체 시도 건수                                                   250
2                성공 건수                                                   243
3
4           [전체] 실 일치율                                         21/243 = 8.6%
5          [전체] 부위 일치율                                       153/243 = 63.0%
6   [전체] 상세부위_정확일치 일치율                                        28/243 = 11.5%
7   [전체] 상세부위_부분일치 일치율                                        34/243 = 14.0%
8        [전체] 하자원인 일치율                                        98/243 = 40.3%
9          [전체] 공종 일치율                                        29/242 = 12.0%
10
11     [빈도 상위5] 부위 일치율                       153/243 = 63.0% (대상: 벽, 천정, 바닥)
12   [빈도 상위5] 하자원인 일치율        98/242 = 40.5% (대상: 시공불량, 흠집, 미시공, 오염, 파손(균열))
13     [빈도 상위5] 공종 일치율  18/174 = 10.3% (대상: 도장공사, 도배공사, 주방가구공사, 내장목공사, 가구공사)

## 21. 정답 vs Nova Pro 판독결과 병기 표

`compute_row`에서 이미 `원본_X` / `AI_X`로 병기해뒀으니, 여기서는 보기 좋게 정렬해서 표시하고 CSV로도 저장합니다.

In [79]:
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.max_rows", None)

display_cols = [
    "defect_id", "동", "호",
    "원본_실", "AI_실", "실_일치",
    "원본_부위", "AI_부위", "부위_일치",
    "원본_상세부위", "AI_상세부위", "상세부위_일치", "상세부위_부분일치",
    "원본_하자원인", "AI_하자원인", "하자원인_일치",
    "원본_공종", "AI_공종", "공종_일치",
    "AI_신뢰도", "분석상태",
]
compare_df = df[display_cols]

CSV_PATH = Path("classification_compare.csv")
compare_df.to_csv(CSV_PATH, index=False, encoding="utf-8-sig")
print(f"병기 비교표 저장: {CSV_PATH.resolve()}")

compare_df

병기 비교표 저장: /content/classification_compare.csv

,defect_id,동,호,원본_실,AI_실,실_일치,원본_부위,AI_부위,부위_일치,원본_상세부위,...,상세부위_일치,상세부위_부분일치,원본_하자원인,AI_하자원인,하자원인_일치,원본_공종,AI_공종,공종_일치,AI_신뢰도,분석상태
0,13052436,104,1501,공용욕실,거실,False,벽,벽,True,타일,...,True,True,흠집,시공불량,False,타일공사,타일공사,True,0.95,성공
1,13052450,103,203,주방발코니,욕실,False,벽,바닥,False,코킹,...,False,False,미시공,시공불량,False,코킹공사,타일공사,False,0.95,성공
2,13052460,103,501,침실1,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.90,성공
3,13052509,104,1503,안방전면발코니,공용부,False,천정,천정,True,도장,...,True,True,미시공,시공불량,False,도장공사,도장공사,True,0.95,성공
4,13052570,104,1501,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
5,13052608,104,1501,안방전면발코니,거실,False,벽,벽,True,빨래건조대스위치,...,False,False,미시공,미시공,True,가전용품공사,내장공사,False,0.90,성공
6,13052609,109,1404,주방,거실,False,벽,벽,True,엔지니어드스톤,...,False,False,시공불량,시공불량,True,엔지니어드스톤공사,타일공사,False,0.95,성공
7,13052638,103,1503,주방,거실,False,벽,벽,True,수납장,...,False,False,흠집,시공불량,False,주방가구공사,목문공사,False,0.95,성공
8,13052667,104,1403,안방,거실,False,벽,벽,True,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
9,13052677,109,1104,침실2,복도,False,천정,벽,False,천정지,...,False,False,시공불량,오염,False,도배공사,도배공사,True,0.95,성공
10,13052680,104,1504,현관,공용부,False,바닥,벽,False,디딤판,...,False,False,시공불량,시공불량,True,인조강화석공사,코킹공사,False,0.90,성공
11,13052731,109,1204,거실,미분류,False,벽,벽,True,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
12,13052732,103,701,실외기,거실,False,벽,벽,True,스프링클러,...,False,False,미시공,오염,False,소방공사,도장공사,False,0.90,성공
13,13052753,104,1401,침실1,거실,False,벽,벽,True,벽지,...,False,False,흠집,시공불량,False,도배공사,도장공사,False,0.95,성공
14,13052772,103,501,부부욕실,현관,False,벽,벽,True,목문,...,False,False,시공불량,시공불량,True,목문공사,도장공사,False,0.95,성공
15,13052854,104,1303,안방전면발코니,현관,False,바닥,바닥,True,타일,...,True,True,미시공,오염,False,타일공사,타일공사,True,0.95,성공
16,13052894,104,1401,실외기,거실,False,벽,벽,True,도장,...,True,True,흠집,오염,False,도장공사,도장공사,True,0.90,성공
17,13052925,109,1304,현관,공용부,False,벽,벽,True,방화문(도장),...,False,False,흠집,미시공,False,도장공사,통신공사,False,0.95,성공
18,13053076,103,1204,현관,공용부,False,벽,바닥,False,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.90,성공
19,13053092,103,1204,침실2,거실발코니,False,벽,벽,True,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
20,13053113,103,303,거실,거실,True,천정,벽,False,천정지,...,False,False,시공불량,미시공,False,도배공사,내장공사,False,0.95,성공
21,13053157,103,303,부부욕실,거실,False,벽,벽,True,목문,...,False,False,흠집,시공불량,False,목문공사,코킹공사,False,0.95,성공
22,13053167,104,101,공용욕실,욕실1,False,벽,벽,True,젠다이인조석,...,False,False,미시공,시공불량,False,인조강화석공사,타일공사,False,0.95,성공
23,13053176,103,303,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.95,성공
24,13053179,104,303,현관,거실,False,벽,천정,False,벽지,...,False,False,흠집,파손(균열),False,도배공사,내장공사,False,0.95,성공
25,13053228,103,303,주방펜트리,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
26,13053245,103,1204,주방,공용부,False,벽,벽,True,수납장,...,False,False,시공불량,파손(균열),False,주방가구공사,유리공사,False,0.95,성공
27,13053255,103,1204,주방,현관,False,벽,바닥,False,씽크하부장,...,False,False,시공불량,시공불량,True,주방가구공사,마루공사,False,0.95,성공
28,13053264,104,101,주방,None,None,벽,None,None,씽크하부장,...,None,None,미시공,None,None,주방가구공사,None,None,NaN,오류
29,13053286,103,1303,안방전면발코니,미분류,False,벽,벽,True,빨래건조대스위치,...,False,False,미시공,미시공,True,가전용품공사,내장공사,False,0.90,성공
30,13053313,103,1104,현관펜트리,공용부,False,바닥,바닥,True,타일,...,True,True,시공불량,오염,False,타일공사,타일공사,True,0.90,성공
31,13053328,103,403,거실,미분류,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
32,13053331,103,1104,침실2,거실,False,벽,벽,True,목문,...,False,False,흠집,미시공,False,목창호공사,전기공사,False,0.95,성공
33,13053356,104,1301,주방펜트리,공용부,False,천정,천정,True,천정지,...,False,False,흠집,시공불량,False,도배공사,내장공사,False,0.90,성공
34,13053399,103,302,안방,현관,False,벽,문,False,목문,...,True,True,흠집,파손(균열),False,목문공사,목문공사,True,0.95,성공
35,13053403,108,1701,주방발코니,욕실,False,벽,벽,True,수전,...,True,True,파손(균열),시공불량,False,설비공사,위생기구공사,False,0.95,성공
36,13053462,103,403,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,미시공,False,도장공사,위생기구공사,False,0.95,성공
37,13053493,104,1202,공용욕실,욕실,False,벽,벽,True,젠다이인조석,...,False,False,미시공,오염,False,인조강화석공사,거울공사,False,0.95,성공
38,13053497,103,302,안방전면발코니,거실발코니,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
39,13053500,109,1804,주방발코니,거실발코니,False,벽,미분류,False,목문,...,False,False,작동(자재)불량,시공불량,False,목문공사,창호공사,False,0.95,성공
40,13053501,104,403,침실1,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.90,성공
41,13053506,104,1202,침실1,거실,False,벽,벽,True,목문,...,False,False,시공불량,시공불량,True,목문공사,목문공사,True,0.95,성공
42,13053512,104,201,공용욕실,None,None,벽,None,None,젠다이인조석,...,None,None,미시공,None,None,인조강화석공사,None,None,NaN,오류
43,13053524,103,1203,침실2,거실발코니,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
44,13053526,104,403,침실2,거실,False,벽,바닥,False,걸레받이,...,False,False,시공불량,오염,False,내장목공사,기타공사,False,0.80,성공
45,13053544,104,1303,현관,미분류,False,천정,벽,False,천정지,...,False,False,시공불량,파손(균열),False,도배공사,내장공사,False,0.95,성공
46,13053566,104,1303,현관,공용부,False,벽,천정,False,중문(레일),...,False,False,시공불량,시공불량,True,중문공사,코킹공사,False,0.95,성공
47,13053612,104,1202,안방,거실,False,천정,천정,True,천정지,...,True,True,흠집,미시공,False,도배공사,미장공사,False,0.90,성공
48,13053624,109,1804,드레스룸,공용부,False,벽,바닥,False,화장대,...,False,False,시공불량,오염,False,가구공사,마루공사,False,0.90,성공
49,13053644,103,301,주방발코니,거실,False,벽,벽,True,준공청소,...,False,False,흠집,시공불량,False,준공청소,코킹공사,False,0.90,성공
50,13053654,103,1203,주방발코니,현관,False,벽,벽,True,유리(창호),...,True,True,시공불량,오염,False,유리공사,창호공사,False,0.95,성공
51,13053677,103,1001,침실1,현관,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.90,성공
52,13053707,103,404,드레스룸,거실발코니,False,천정,벽,False,몰딩,...,False,False,시공불량,파손(균열),False,내장목공사,코킹공사,False,0.90,성공
53,13053741,104,1303,실외기,공용부,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,도장공사,False,0.90,성공
54,13053754,104,1303,실외기,공용부,False,벽,천정,False,도장,...,True,True,시공불량,오염,False,도장공사,도장공사,True,0.95,성공
55,13053767,103,402,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.90,성공
56,13053778,103,403,거실,계단실(내부),False,바닥,벽,False,강마루84,...,False,False,미시공,미시공,True,마루공사,미장공사,False,0.95,성공
57,13053812,103,201,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
58,13053813,109,1904,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
59,13053832,104,404,주방,미분류,False,벽,바닥,False,걸레받이,...,False,False,시공불량,미시공,False,내장목공사,기타공사,False,0.90,성공
60,13053847,108,1701,현관,거실발코니,False,천정,벽,False,도장,...,False,False,오염,시공불량,False,도장공사,코킹공사,False,0.95,성공
61,13053869,104,1204,주방,거실,False,벽,벽,True,씽크상부장,...,False,False,시공불량,미시공,False,주방가구공사,도장공사,False,0.90,성공
62,13053879,108,1801,주방발코니,거실,False,벽,벽,True,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
63,13053935,103,503,안방전면발코니,욕실,False,벽,벽,True,도장,...,True,True,시공불량,미시공,False,도장공사,도장공사,True,0.90,성공
64,13053937,104,302,거실,현관,False,천정,벽,False,환기구(캡),...,False,False,미시공,파손(균열),False,환기시스템공사,목창호공사,False,0.95,성공
65,13053991,103,402,공용욕실,부부욕실,False,벽,벽,True,젠다이인조석,...,False,False,시공불량,흠집,False,인조강화석공사,타일공사,False,0.95,성공
66,13053994,109,2004,주방,주방,True,벽,벽,True,코킹(타일),...,False,True,시공불량,미시공,False,주방가구공사,타일공사,False,0.95,성공
67,13054002,103,904,주방,공용부,False,벽,벽,True,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
68,13054012,103,1101,주방,거실,False,벽,벽,True,수납장,...,False,False,흠집,파손(균열),False,주방가구공사,목공사,False,0.95,성공
69,13054050,103,804,현관,공용부,False,벽,벽,True,걸레받이(대리석),...,False,False,시공불량,파손(균열),False,인조강화석공사,코킹공사,False,0.90,성공
70,13054077,104,503,침실1,거실,False,벽,천정,False,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.95,성공
71,13054083,104,1203,침실2,거실,False,벽,천정,False,벽지,...,False,False,시공불량,시공불량,True,도배공사,도장공사,False,0.90,성공
72,13054097,103,1003,침실2,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
73,13054107,103,101,부부욕실,욕실,False,벽,미분류,False,변기,...,True,True,미시공,오염,False,설비공사,위생기구공사,False,0.95,성공
74,13054130,103,804,안방전면발코니,거실,False,천정,벽,False,도장,...,True,True,시공불량,오염,False,도장공사,도장공사,True,0.80,성공
75,13054138,104,502,드레스룸,거실발코니,False,벽,천정,False,PL창,...,False,False,시공불량,오염,False,창호공사,창호공사,True,0.95,성공
76,13054186,104,1002,안방,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
77,13054187,103,504,주방발코니,미분류,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
78,13054197,103,804,주방,거실,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
79,13054202,109,2104,침실2,거실,False,벽,벽,True,PL창,...,False,True,시공불량,오염,False,창호공사,코킹공사,False,0.90,성공
80,13054208,104,1002,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.90,성공
81,13054209,103,504,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
82,13054210,104,1001,주방,거실,False,천정,천정,True,몰딩,...,False,False,흠집,시공불량,False,내장목공사,내장공사,False,0.90,성공
83,13054214,103,804,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.95,성공
84,13054238,104,901,현관,공용부,False,벽,천정,False,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
85,13054249,103,502,현관,현관,True,벽,바닥,False,코킹,...,False,False,시공불량,시공불량,True,코킹공사,타일공사,False,0.90,성공
86,13054255,104,502,주방,거실,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
87,13054269,109,2104,주방,주방,True,벽,벽,True,냉장고장,...,False,False,시공불량,미시공,False,주방가구공사,전기공사,False,0.95,성공
88,13054272,104,1002,주방발코니,거실,False,벽,벽,True,코킹,...,True,True,시공불량,시공불량,True,코킹공사,코킹공사,True,0.90,성공
89,13054291,103,504,거실,거실,True,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.95,성공
90,13054292,103,1201,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.95,성공
91,13054332,109,2104,안방,욕실,False,벽,천정,False,PL창,...,False,False,시공불량,파손(균열),False,창호공사,유리공사,False,0.90,성공
92,13054337,104,402,침실2,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.95,성공
93,13054376,103,101,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,파손(균열),False,도장공사,미장공사,False,0.95,성공
94,13054425,103,903,드레스룸,현관,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
95,13054442,104,901,주방발코니,거실,False,벽,천정,False,도장,...,False,False,흠집,시공불량,False,도장공사,내장공사,False,0.90,성공
96,13054454,104,402,안방,거실,False,천정,천정,True,천정지,...,True,True,시공불량,파손(균열),False,도배공사,내장공사,False,0.95,성공
97,13054465,104,402,안방전면발코니,거실,False,벽,벽,True,도장,...,True,True,오염,오염,True,도장공사,도장공사,True,0.90,성공
98,13054480,104,504,침실1,거실,False,벽,천정,False,준공청소,...,False,False,오염,파손(균열),False,준공청소,코킹공사,False,0.90,성공
99,13054482,104,902,침실2,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
100,13054491,103,101,주방발코니,욕실,False,벽,벽,True,단열보드,...,False,False,시공불량,미시공,False,단열공사,위생기구공사,False,0.95,성공
101,13054515,104,603,현관,공용부,False,벽,벽,True,방화문틀(도장),...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
102,13054531,103,1301,현관,거실,False,벽,천정,False,방화문틀(도장),...,False,True,오염,미시공,False,도장공사,도장공사,True,0.90,성공
103,13054533,109,2204,실외기,욕실,False,벽,바닥,False,도장,...,False,False,시공불량,오염,False,도장공사,타일공사,False,0.95,성공
104,13054566,103,604,침실1,거실,False,벽,벽,True,준공청소,...,False,False,오염,오염,True,준공청소,도장공사,False,0.90,성공
105,13054572,103,1301,안방전면발코니,부부욕실,False,벽,벽,True,도장,...,False,False,오염,미시공,False,도장공사,위생기구공사,False,0.95,성공
106,13054575,103,604,침실2,거실,False,벽,벽,True,붙박이장,...,True,True,미시공,시공불량,False,가구공사,내장공사,False,0.95,성공
107,13054578,108,1901,안방,공용부,False,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장목공사,False,0.95,성공
108,13054590,103,602,안방,미분류,False,벽,벽,True,벽지,...,False,False,시공불량,미시공,False,도배공사,전기공사,False,0.95,성공
109,13054612,103,604,주방펜트리,거실,False,천정,천정,True,몰딩,...,False,False,시공불량,오염,False,내장목공사,내장공사,False,0.90,성공
110,13054646,103,604,주방,거실발코니,False,벽,천정,False,씽크상부장,...,False,False,미시공,시공불량,False,주방가구공사,코킹공사,False,0.90,성공
111,13054652,103,604,주방,거실,False,천정,벽,False,천정지,...,False,False,미시공,시공불량,False,도배공사,도장공사,False,0.90,성공
112,13054707,104,402,주방,거실발코니,False,벽,벽,True,PL창,...,False,False,시공불량,시공불량,True,창호공사,발코니난간공사,False,0.95,성공
113,13054712,104,603,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,위생기구공사,False,0.90,성공
114,13054736,104,402,주방,현관,False,천정,벽,False,천정지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.90,성공
115,13054746,104,1103,침실1,거실,False,벽,천정,False,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.95,성공
116,13054767,104,604,현관,현관,True,벽,벽,True,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
117,13054772,104,1103,침실1,거실,False,천정,벽,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,도배공사,True,0.95,성공
118,13054817,103,1304,주방펜트리,None,None,천정,None,None,몰딩,...,None,None,흠집,None,None,내장목공사,None,None,NaN,오류
119,13054820,104,604,주방,거실,False,벽,벽,True,씽크하부장,...,False,False,시공불량,오염,False,주방가구공사,도장공사,False,0.80,성공
120,13054858,103,1401,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.90,성공
121,13054883,104,804,공용욕실,욕실1,False,벽,벽,True,변기,...,False,False,미시공,오염,False,설비공사,타일공사,False,0.95,성공
122,13054942,104,1003,주방발코니,거실,False,천정,벽,False,단열보드,...,False,False,시공불량,미시공,False,단열공사,환기시스템공사,False,0.95,성공
123,13054969,104,301,주방발코니,현관,False,벽,벽,True,코킹,...,True,True,시공불량,오염,False,코킹공사,코킹공사,True,0.90,성공
124,13054971,104,1003,주방발코니,거실,False,벽,벽,True,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
125,13054998,103,1202,현관,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
126,13055045,103,703,침실1,거실발코니,False,벽,벽,True,PL창,...,False,False,흠집,파손(균열),False,창호공사,코킹공사,False,0.95,성공
127,13055101,103,1102,주방발코니,거실발코니,False,벽,미분류,False,코킹(유리),...,False,True,시공불량,시공불량,True,유리공사,코킹공사,False,0.90,성공
128,13055111,103,1102,침실2,거실,False,천정,천정,True,천정지,...,True,True,시공불량,미시공,False,도배공사,내장공사,False,0.95,성공
129,13055113,109,2102,현관,거실,False,벽,벽,True,신발장,...,False,False,시공불량,오염,False,가구공사,도장공사,False,0.90,성공
130,13055133,109,2002,현관펜트리,거실,False,벽,천정,False,펜트리문,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
131,13055138,109,2002,침실1,현관,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,기타공사,False,0.90,성공
132,13055143,106,1104,현관,거실,False,벽,천정,False,신발장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
133,13055150,104,903,현관,공용부,False,벽,바닥,False,방화문틀(도장),...,False,False,흠집,오염,False,도장공사,마감사인물공사,False,0.80,성공
134,13055171,108,2103,거실,거실,True,벽,벽,True,벽지,...,False,False,시공불량,파손(균열),False,도배공사,내장공사,False,0.90,성공
135,13055180,109,2002,침실2,거실,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,기타공사,False,0.90,성공
136,13055206,108,302,주방,주방,True,벽,벽,True,씽크상부장,...,False,False,미시공,미시공,True,주방가구공사,렌지후드공사,False,0.95,성공
137,13055221,109,2102,주방발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
138,13055233,104,903,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,위생기구공사,False,0.95,성공
139,13055298,109,2002,안방전면발코니,거실,False,벽,벽,True,도장,...,True,True,파손(균열),파손(균열),True,도장공사,도장공사,True,0.90,성공
140,13055301,104,401,현관,공용부,False,천정,천정,True,천정지,...,False,False,시공불량,미시공,False,도배공사,코킹공사,False,0.90,성공
141,13055311,103,702,안방,거실발코니,False,천정,미분류,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
142,13055333,108,402,침실1,현관,False,벽,벽,True,PL창,...,False,False,흠집,시공불량,False,창호공사,목문공사,False,0.95,성공
143,13055335,108,601,침실1,거실,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,내장공사,False,0.90,성공
144,13055341,103,702,거실복도,거실,False,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.95,성공
145,13055350,109,2002,주방발코니,거실,False,벽,천정,False,도장,...,False,False,오염,누수,False,도장공사,내장공사,False,0.90,성공
146,13055358,108,603,주방,주방,True,벽,천정,False,아일랜드식탁장,...,False,False,미시공,시공불량,False,주방가구공사,코킹공사,False,0.90,성공
147,13055363,108,601,안방전면발코니,공용부,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
148,13055384,104,401,침실1,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.90,성공
149,13055406,108,601,실외기,거실,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,미장공사,False,0.90,성공
150,13055450,108,402,거실,거실발코니,False,벽,벽,True,도장(외부),...,False,False,미시공,시공불량,False,도장공사,발코니난간공사,False,0.95,성공
151,13055469,108,703,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
152,13055476,108,402,거실,거실발코니,False,벽,벽,True,PL창,...,False,False,흠집,시공불량,False,창호공사,코킹공사,False,0.95,성공
153,13055483,104,803,주방,현관,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
154,13055496,108,703,안방,거실,False,벽,천정,False,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
155,13055504,108,801,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
156,13055534,108,601,주방,공용부,False,벽,바닥,False,수납장,...,False,False,미시공,시공불량,False,주방가구공사,타일공사,False,0.95,성공
157,13055537,109,2202,주방발코니,거실발코니,False,벽,미분류,False,PL창,...,True,True,시공불량,시공불량,True,창호공사,창호공사,True,0.95,성공
158,13055554,108,801,주방,주방,True,벽,벽,True,씽크상부장,...,False,False,시공불량,미시공,False,주방가구공사,잡철물공사,False,0.95,성공
159,13055562,106,1204,드레스룸,거실,False,벽,천정,False,화장대,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
160,13055575,108,402,주방,주방,True,벽,바닥,False,씽크상부장,...,False,False,미시공,미시공,True,주방가구공사,마루공사,False,0.90,성공
161,13055585,108,703,주방,공용부,False,벽,벽,True,씽크하부장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
162,13055603,106,1204,주방,거실발코니,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,창호공사,False,0.90,성공
163,13055619,104,401,부부욕실,욕실1,False,벽,천정,False,세면대상판(인조),...,False,False,미시공,시공불량,False,석공사,욕실천정공사,False,0.95,성공
164,13055662,109,2302,현관펜트리,거실,False,벽,바닥,False,펜트리문,...,False,False,시공불량,미시공,False,가구공사,내장공사,False,0.90,성공
165,13055683,103,802,침실2,현관,False,천정,벽,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장목공사,False,0.95,성공
166,13055684,108,501,주방,거실,False,벽,벽,True,수납장,...,False,False,미시공,시공불량,False,주방가구공사,내장공사,False,0.95,성공
167,13055687,108,1304,현관,공용부,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,내장공사,코킹공사,False,0.95,성공
168,13055705,108,1903,실외기,공용부,False,천정,벽,False,도장,...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.90,성공
169,13055724,108,803,침실1,거실,False,천정,천정,True,천정지,...,False,False,시공불량,오염,False,도배공사,내장목공사,False,0.90,성공
170,13055732,108,403,침실1,거실,False,벽,벽,True,붙박이장,...,False,False,흠집,시공불량,False,가구공사,코킹공사,False,0.95,성공
171,13055752,108,1903,드레스룸,거실발코니,False,벽,벽,True,화장대상판(인조),...,False,False,흠집,시공불량,False,인조강화석공사,창호공사,False,0.95,성공
172,13055772,108,1304,침실2,현관,False,벽,벽,True,목문,...,False,False,흠집,시공불량,False,목창호공사,목문공사,False,0.90,성공
173,13055817,108,303,거실,거실,True,바닥,벽,False,강마루84,...,False,False,미시공,오염,False,마루공사,도장공사,False,0.90,성공
174,13055826,108,901,주방발코니,거실,False,천정,벽,False,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
175,13055831,103,802,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.80,성공
176,13055833,109,2302,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,파손(균열),False,도배공사,미장공사,False,0.90,성공
177,13055837,108,901,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,미시공,False,내장목공사,전기공사,False,0.95,성공
178,13055839,108,501,침실1,거실,False,벽,벽,True,벽지,...,False,False,시공불량,결로,False,도배공사,도장공사,False,0.90,성공
179,13055855,109,2302,주방,주방,True,벽,바닥,False,씽크상부장,...,False,False,시공불량,파손(균열),False,주방가구공사,엔지니어드스톤공사,False,0.95,성공
180,13055868,108,1304,거실복도,거실,False,벽,천정,False,벽지,...,False,False,시공불량,파손(균열),False,도배공사,도장공사,False,0.90,성공
181,13055891,104,703,주방,공용부,False,벽,천정,False,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
182,13055916,106,1304,주방발코니,거실,False,천정,천정,True,천정면(내장),...,True,True,시공불량,시공불량,True,내장목공사,내장공사,False,0.90,성공
183,13055927,104,501,거실,거실,True,벽,벽,True,준공청소,...,False,False,오염,오염,True,준공청소,코킹공사,False,0.90,성공
184,13055937,104,304,안방,거실발코니,False,벽,벽,True,바탕면(내장),...,False,False,오염,시공불량,False,내장목공사,코킹공사,False,0.90,성공
185,13055947,104,304,안방,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,기타공사,False,0.90,성공
186,13055962,108,1304,부부욕실,부부욕실,True,벽,벽,True,욕실장,...,False,False,미시공,파손(균열),False,욕실가구공사,타일공사,False,0.90,성공
187,13055966,104,304,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,시공불량,True,도장공사,미장공사,False,0.95,성공
188,13056012,108,1001,안방,거실발코니,False,천정,미분류,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
189,13056025,108,803,주방,거실,False,벽,벽,True,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공

### 21-1. 5개 항목 중 하나라도 불일치한 건만 모아보기

In [80]:
match_cols = ["실_일치", "부위_일치", "상세부위_일치", "하자원인_일치", "공종_일치"]
mismatch_mask = compare_df[match_cols].apply(lambda row: any(v is False for v in row), axis=1)
mismatch_df = compare_df[mismatch_mask]
print(f"불일치 건수: {len(mismatch_df)} / {len(compare_df)}건")
mismatch_df

불일치 건수: 243 / 250건

,defect_id,동,호,원본_실,AI_실,실_일치,원본_부위,AI_부위,부위_일치,원본_상세부위,...,상세부위_일치,상세부위_부분일치,원본_하자원인,AI_하자원인,하자원인_일치,원본_공종,AI_공종,공종_일치,AI_신뢰도,분석상태
0,13052436,104,1501,공용욕실,거실,False,벽,벽,True,타일,...,True,True,흠집,시공불량,False,타일공사,타일공사,True,0.95,성공
1,13052450,103,203,주방발코니,욕실,False,벽,바닥,False,코킹,...,False,False,미시공,시공불량,False,코킹공사,타일공사,False,0.95,성공
2,13052460,103,501,침실1,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.90,성공
3,13052509,104,1503,안방전면발코니,공용부,False,천정,천정,True,도장,...,True,True,미시공,시공불량,False,도장공사,도장공사,True,0.95,성공
4,13052570,104,1501,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
5,13052608,104,1501,안방전면발코니,거실,False,벽,벽,True,빨래건조대스위치,...,False,False,미시공,미시공,True,가전용품공사,내장공사,False,0.90,성공
6,13052609,109,1404,주방,거실,False,벽,벽,True,엔지니어드스톤,...,False,False,시공불량,시공불량,True,엔지니어드스톤공사,타일공사,False,0.95,성공
7,13052638,103,1503,주방,거실,False,벽,벽,True,수납장,...,False,False,흠집,시공불량,False,주방가구공사,목문공사,False,0.95,성공
8,13052667,104,1403,안방,거실,False,벽,벽,True,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
9,13052677,109,1104,침실2,복도,False,천정,벽,False,천정지,...,False,False,시공불량,오염,False,도배공사,도배공사,True,0.95,성공
10,13052680,104,1504,현관,공용부,False,바닥,벽,False,디딤판,...,False,False,시공불량,시공불량,True,인조강화석공사,코킹공사,False,0.90,성공
11,13052731,109,1204,거실,미분류,False,벽,벽,True,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
12,13052732,103,701,실외기,거실,False,벽,벽,True,스프링클러,...,False,False,미시공,오염,False,소방공사,도장공사,False,0.90,성공
13,13052753,104,1401,침실1,거실,False,벽,벽,True,벽지,...,False,False,흠집,시공불량,False,도배공사,도장공사,False,0.95,성공
14,13052772,103,501,부부욕실,현관,False,벽,벽,True,목문,...,False,False,시공불량,시공불량,True,목문공사,도장공사,False,0.95,성공
15,13052854,104,1303,안방전면발코니,현관,False,바닥,바닥,True,타일,...,True,True,미시공,오염,False,타일공사,타일공사,True,0.95,성공
16,13052894,104,1401,실외기,거실,False,벽,벽,True,도장,...,True,True,흠집,오염,False,도장공사,도장공사,True,0.90,성공
17,13052925,109,1304,현관,공용부,False,벽,벽,True,방화문(도장),...,False,False,흠집,미시공,False,도장공사,통신공사,False,0.95,성공
18,13053076,103,1204,현관,공용부,False,벽,바닥,False,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.90,성공
19,13053092,103,1204,침실2,거실발코니,False,벽,벽,True,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
20,13053113,103,303,거실,거실,True,천정,벽,False,천정지,...,False,False,시공불량,미시공,False,도배공사,내장공사,False,0.95,성공
21,13053157,103,303,부부욕실,거실,False,벽,벽,True,목문,...,False,False,흠집,시공불량,False,목문공사,코킹공사,False,0.95,성공
22,13053167,104,101,공용욕실,욕실1,False,벽,벽,True,젠다이인조석,...,False,False,미시공,시공불량,False,인조강화석공사,타일공사,False,0.95,성공
23,13053176,103,303,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.95,성공
24,13053179,104,303,현관,거실,False,벽,천정,False,벽지,...,False,False,흠집,파손(균열),False,도배공사,내장공사,False,0.95,성공
25,13053228,103,303,주방펜트리,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
26,13053245,103,1204,주방,공용부,False,벽,벽,True,수납장,...,False,False,시공불량,파손(균열),False,주방가구공사,유리공사,False,0.95,성공
27,13053255,103,1204,주방,현관,False,벽,바닥,False,씽크하부장,...,False,False,시공불량,시공불량,True,주방가구공사,마루공사,False,0.95,성공
29,13053286,103,1303,안방전면발코니,미분류,False,벽,벽,True,빨래건조대스위치,...,False,False,미시공,미시공,True,가전용품공사,내장공사,False,0.90,성공
30,13053313,103,1104,현관펜트리,공용부,False,바닥,바닥,True,타일,...,True,True,시공불량,오염,False,타일공사,타일공사,True,0.90,성공
31,13053328,103,403,거실,미분류,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
32,13053331,103,1104,침실2,거실,False,벽,벽,True,목문,...,False,False,흠집,미시공,False,목창호공사,전기공사,False,0.95,성공
33,13053356,104,1301,주방펜트리,공용부,False,천정,천정,True,천정지,...,False,False,흠집,시공불량,False,도배공사,내장공사,False,0.90,성공
34,13053399,103,302,안방,현관,False,벽,문,False,목문,...,True,True,흠집,파손(균열),False,목문공사,목문공사,True,0.95,성공
35,13053403,108,1701,주방발코니,욕실,False,벽,벽,True,수전,...,True,True,파손(균열),시공불량,False,설비공사,위생기구공사,False,0.95,성공
36,13053462,103,403,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,미시공,False,도장공사,위생기구공사,False,0.95,성공
37,13053493,104,1202,공용욕실,욕실,False,벽,벽,True,젠다이인조석,...,False,False,미시공,오염,False,인조강화석공사,거울공사,False,0.95,성공
38,13053497,103,302,안방전면발코니,거실발코니,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,코킹공사,False,0.95,성공
39,13053500,109,1804,주방발코니,거실발코니,False,벽,미분류,False,목문,...,False,False,작동(자재)불량,시공불량,False,목문공사,창호공사,False,0.95,성공
40,13053501,104,403,침실1,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.90,성공
41,13053506,104,1202,침실1,거실,False,벽,벽,True,목문,...,False,False,시공불량,시공불량,True,목문공사,목문공사,True,0.95,성공
43,13053524,103,1203,침실2,거실발코니,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
44,13053526,104,403,침실2,거실,False,벽,바닥,False,걸레받이,...,False,False,시공불량,오염,False,내장목공사,기타공사,False,0.80,성공
45,13053544,104,1303,현관,미분류,False,천정,벽,False,천정지,...,False,False,시공불량,파손(균열),False,도배공사,내장공사,False,0.95,성공
46,13053566,104,1303,현관,공용부,False,벽,천정,False,중문(레일),...,False,False,시공불량,시공불량,True,중문공사,코킹공사,False,0.95,성공
47,13053612,104,1202,안방,거실,False,천정,천정,True,천정지,...,True,True,흠집,미시공,False,도배공사,미장공사,False,0.90,성공
48,13053624,109,1804,드레스룸,공용부,False,벽,바닥,False,화장대,...,False,False,시공불량,오염,False,가구공사,마루공사,False,0.90,성공
49,13053644,103,301,주방발코니,거실,False,벽,벽,True,준공청소,...,False,False,흠집,시공불량,False,준공청소,코킹공사,False,0.90,성공
50,13053654,103,1203,주방발코니,현관,False,벽,벽,True,유리(창호),...,True,True,시공불량,오염,False,유리공사,창호공사,False,0.95,성공
51,13053677,103,1001,침실1,현관,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.90,성공
52,13053707,103,404,드레스룸,거실발코니,False,천정,벽,False,몰딩,...,False,False,시공불량,파손(균열),False,내장목공사,코킹공사,False,0.90,성공
53,13053741,104,1303,실외기,공용부,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,도장공사,False,0.90,성공
54,13053754,104,1303,실외기,공용부,False,벽,천정,False,도장,...,True,True,시공불량,오염,False,도장공사,도장공사,True,0.95,성공
55,13053767,103,402,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.90,성공
56,13053778,103,403,거실,계단실(내부),False,바닥,벽,False,강마루84,...,False,False,미시공,미시공,True,마루공사,미장공사,False,0.95,성공
57,13053812,103,201,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
58,13053813,109,1904,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
59,13053832,104,404,주방,미분류,False,벽,바닥,False,걸레받이,...,False,False,시공불량,미시공,False,내장목공사,기타공사,False,0.90,성공
60,13053847,108,1701,현관,거실발코니,False,천정,벽,False,도장,...,False,False,오염,시공불량,False,도장공사,코킹공사,False,0.95,성공
61,13053869,104,1204,주방,거실,False,벽,벽,True,씽크상부장,...,False,False,시공불량,미시공,False,주방가구공사,도장공사,False,0.90,성공
62,13053879,108,1801,주방발코니,거실,False,벽,벽,True,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
63,13053935,103,503,안방전면발코니,욕실,False,벽,벽,True,도장,...,True,True,시공불량,미시공,False,도장공사,도장공사,True,0.90,성공
64,13053937,104,302,거실,현관,False,천정,벽,False,환기구(캡),...,False,False,미시공,파손(균열),False,환기시스템공사,목창호공사,False,0.95,성공
65,13053991,103,402,공용욕실,부부욕실,False,벽,벽,True,젠다이인조석,...,False,False,시공불량,흠집,False,인조강화석공사,타일공사,False,0.95,성공
66,13053994,109,2004,주방,주방,True,벽,벽,True,코킹(타일),...,False,True,시공불량,미시공,False,주방가구공사,타일공사,False,0.95,성공
67,13054002,103,904,주방,공용부,False,벽,벽,True,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
68,13054012,103,1101,주방,거실,False,벽,벽,True,수납장,...,False,False,흠집,파손(균열),False,주방가구공사,목공사,False,0.95,성공
69,13054050,103,804,현관,공용부,False,벽,벽,True,걸레받이(대리석),...,False,False,시공불량,파손(균열),False,인조강화석공사,코킹공사,False,0.90,성공
70,13054077,104,503,침실1,거실,False,벽,천정,False,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.95,성공
71,13054083,104,1203,침실2,거실,False,벽,천정,False,벽지,...,False,False,시공불량,시공불량,True,도배공사,도장공사,False,0.90,성공
72,13054097,103,1003,침실2,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
73,13054107,103,101,부부욕실,욕실,False,벽,미분류,False,변기,...,True,True,미시공,오염,False,설비공사,위생기구공사,False,0.95,성공
74,13054130,103,804,안방전면발코니,거실,False,천정,벽,False,도장,...,True,True,시공불량,오염,False,도장공사,도장공사,True,0.80,성공
75,13054138,104,502,드레스룸,거실발코니,False,벽,천정,False,PL창,...,False,False,시공불량,오염,False,창호공사,창호공사,True,0.95,성공
76,13054186,104,1002,안방,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,마루공사,False,0.90,성공
77,13054187,103,504,주방발코니,미분류,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
78,13054197,103,804,주방,거실,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
79,13054202,109,2104,침실2,거실,False,벽,벽,True,PL창,...,False,True,시공불량,오염,False,창호공사,코킹공사,False,0.90,성공
80,13054208,104,1002,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.90,성공
81,13054209,103,504,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
82,13054210,104,1001,주방,거실,False,천정,천정,True,몰딩,...,False,False,흠집,시공불량,False,내장목공사,내장공사,False,0.90,성공
83,13054214,103,804,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,시공불량,True,내장목공사,위생기구공사,False,0.95,성공
84,13054238,104,901,현관,공용부,False,벽,천정,False,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
85,13054249,103,502,현관,현관,True,벽,바닥,False,코킹,...,False,False,시공불량,시공불량,True,코킹공사,타일공사,False,0.90,성공
86,13054255,104,502,주방,거실,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
87,13054269,109,2104,주방,주방,True,벽,벽,True,냉장고장,...,False,False,시공불량,미시공,False,주방가구공사,전기공사,False,0.95,성공
88,13054272,104,1002,주방발코니,거실,False,벽,벽,True,코킹,...,True,True,시공불량,시공불량,True,코킹공사,코킹공사,True,0.90,성공
89,13054291,103,504,거실,거실,True,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.95,성공
90,13054292,103,1201,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.95,성공
91,13054332,109,2104,안방,욕실,False,벽,천정,False,PL창,...,False,False,시공불량,파손(균열),False,창호공사,유리공사,False,0.90,성공
92,13054337,104,402,침실2,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.95,성공
93,13054376,103,101,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,파손(균열),False,도장공사,미장공사,False,0.95,성공
94,13054425,103,903,드레스룸,현관,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
95,13054442,104,901,주방발코니,거실,False,벽,천정,False,도장,...,False,False,흠집,시공불량,False,도장공사,내장공사,False,0.90,성공
96,13054454,104,402,안방,거실,False,천정,천정,True,천정지,...,True,True,시공불량,파손(균열),False,도배공사,내장공사,False,0.95,성공
97,13054465,104,402,안방전면발코니,거실,False,벽,벽,True,도장,...,True,True,오염,오염,True,도장공사,도장공사,True,0.90,성공
98,13054480,104,504,침실1,거실,False,벽,천정,False,준공청소,...,False,False,오염,파손(균열),False,준공청소,코킹공사,False,0.90,성공
99,13054482,104,902,침실2,거실,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.95,성공
100,13054491,103,101,주방발코니,욕실,False,벽,벽,True,단열보드,...,False,False,시공불량,미시공,False,단열공사,위생기구공사,False,0.95,성공
101,13054515,104,603,현관,공용부,False,벽,벽,True,방화문틀(도장),...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
102,13054531,103,1301,현관,거실,False,벽,천정,False,방화문틀(도장),...,False,True,오염,미시공,False,도장공사,도장공사,True,0.90,성공
103,13054533,109,2204,실외기,욕실,False,벽,바닥,False,도장,...,False,False,시공불량,오염,False,도장공사,타일공사,False,0.95,성공
104,13054566,103,604,침실1,거실,False,벽,벽,True,준공청소,...,False,False,오염,오염,True,준공청소,도장공사,False,0.90,성공
105,13054572,103,1301,안방전면발코니,부부욕실,False,벽,벽,True,도장,...,False,False,오염,미시공,False,도장공사,위생기구공사,False,0.95,성공
106,13054575,103,604,침실2,거실,False,벽,벽,True,붙박이장,...,True,True,미시공,시공불량,False,가구공사,내장공사,False,0.95,성공
107,13054578,108,1901,안방,공용부,False,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장목공사,False,0.95,성공
108,13054590,103,602,안방,미분류,False,벽,벽,True,벽지,...,False,False,시공불량,미시공,False,도배공사,전기공사,False,0.95,성공
109,13054612,103,604,주방펜트리,거실,False,천정,천정,True,몰딩,...,False,False,시공불량,오염,False,내장목공사,내장공사,False,0.90,성공
110,13054646,103,604,주방,거실발코니,False,벽,천정,False,씽크상부장,...,False,False,미시공,시공불량,False,주방가구공사,코킹공사,False,0.90,성공
111,13054652,103,604,주방,거실,False,천정,벽,False,천정지,...,False,False,미시공,시공불량,False,도배공사,도장공사,False,0.90,성공
112,13054707,104,402,주방,거실발코니,False,벽,벽,True,PL창,...,False,False,시공불량,시공불량,True,창호공사,발코니난간공사,False,0.95,성공
113,13054712,104,603,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,위생기구공사,False,0.90,성공
114,13054736,104,402,주방,현관,False,천정,벽,False,천정지,...,False,False,시공불량,오염,False,도배공사,도장공사,False,0.90,성공
115,13054746,104,1103,침실1,거실,False,벽,천정,False,붙박이장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.95,성공
116,13054767,104,604,현관,현관,True,벽,벽,True,방화문틀(도장),...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.95,성공
117,13054772,104,1103,침실1,거실,False,천정,벽,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,도배공사,True,0.95,성공
119,13054820,104,604,주방,거실,False,벽,벽,True,씽크하부장,...,False,False,시공불량,오염,False,주방가구공사,도장공사,False,0.80,성공
120,13054858,103,1401,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,코킹공사,False,0.90,성공
121,13054883,104,804,공용욕실,욕실1,False,벽,벽,True,변기,...,False,False,미시공,오염,False,설비공사,타일공사,False,0.95,성공
122,13054942,104,1003,주방발코니,거실,False,천정,벽,False,단열보드,...,False,False,시공불량,미시공,False,단열공사,환기시스템공사,False,0.95,성공
123,13054969,104,301,주방발코니,현관,False,벽,벽,True,코킹,...,True,True,시공불량,오염,False,코킹공사,코킹공사,True,0.90,성공
124,13054971,104,1003,주방발코니,거실,False,벽,벽,True,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
125,13054998,103,1202,현관,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
126,13055045,103,703,침실1,거실발코니,False,벽,벽,True,PL창,...,False,False,흠집,파손(균열),False,창호공사,코킹공사,False,0.95,성공
127,13055101,103,1102,주방발코니,거실발코니,False,벽,미분류,False,코킹(유리),...,False,True,시공불량,시공불량,True,유리공사,코킹공사,False,0.90,성공
128,13055111,103,1102,침실2,거실,False,천정,천정,True,천정지,...,True,True,시공불량,미시공,False,도배공사,내장공사,False,0.95,성공
129,13055113,109,2102,현관,거실,False,벽,벽,True,신발장,...,False,False,시공불량,오염,False,가구공사,도장공사,False,0.90,성공
130,13055133,109,2002,현관펜트리,거실,False,벽,천정,False,펜트리문,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
131,13055138,109,2002,침실1,현관,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,기타공사,False,0.90,성공
132,13055143,106,1104,현관,거실,False,벽,천정,False,신발장,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
133,13055150,104,903,현관,공용부,False,벽,바닥,False,방화문틀(도장),...,False,False,흠집,오염,False,도장공사,마감사인물공사,False,0.80,성공
134,13055171,108,2103,거실,거실,True,벽,벽,True,벽지,...,False,False,시공불량,파손(균열),False,도배공사,내장공사,False,0.90,성공
135,13055180,109,2002,침실2,거실,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,기타공사,False,0.90,성공
136,13055206,108,302,주방,주방,True,벽,벽,True,씽크상부장,...,False,False,미시공,미시공,True,주방가구공사,렌지후드공사,False,0.95,성공
137,13055221,109,2102,주방발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.95,성공
138,13055233,104,903,주방발코니,욕실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,위생기구공사,False,0.95,성공
139,13055298,109,2002,안방전면발코니,거실,False,벽,벽,True,도장,...,True,True,파손(균열),파손(균열),True,도장공사,도장공사,True,0.90,성공
140,13055301,104,401,현관,공용부,False,천정,천정,True,천정지,...,False,False,시공불량,미시공,False,도배공사,코킹공사,False,0.90,성공
141,13055311,103,702,안방,거실발코니,False,천정,미분류,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
142,13055333,108,402,침실1,현관,False,벽,벽,True,PL창,...,False,False,흠집,시공불량,False,창호공사,목문공사,False,0.95,성공
143,13055335,108,601,침실1,거실,False,벽,바닥,False,벽지,...,False,False,시공불량,오염,False,도배공사,내장공사,False,0.90,성공
144,13055341,103,702,거실복도,거실,False,천정,천정,True,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.95,성공
145,13055350,109,2002,주방발코니,거실,False,벽,천정,False,도장,...,False,False,오염,누수,False,도장공사,내장공사,False,0.90,성공
146,13055358,108,603,주방,주방,True,벽,천정,False,아일랜드식탁장,...,False,False,미시공,시공불량,False,주방가구공사,코킹공사,False,0.90,성공
147,13055363,108,601,안방전면발코니,공용부,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
148,13055384,104,401,침실1,거실,False,벽,벽,True,벽지,...,False,False,오염,오염,True,도배공사,도장공사,False,0.90,성공
149,13055406,108,601,실외기,거실,False,벽,벽,True,도장,...,False,False,시공불량,파손(균열),False,도장공사,미장공사,False,0.90,성공
150,13055450,108,402,거실,거실발코니,False,벽,벽,True,도장(외부),...,False,False,미시공,시공불량,False,도장공사,발코니난간공사,False,0.95,성공
151,13055469,108,703,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
152,13055476,108,402,거실,거실발코니,False,벽,벽,True,PL창,...,False,False,흠집,시공불량,False,창호공사,코킹공사,False,0.95,성공
153,13055483,104,803,주방,현관,False,벽,벽,True,수납장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
154,13055496,108,703,안방,거실,False,벽,천정,False,벽지,...,False,False,시공불량,시공불량,True,도배공사,코킹공사,False,0.90,성공
155,13055504,108,801,안방전면발코니,거실발코니,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.90,성공
156,13055534,108,601,주방,공용부,False,벽,바닥,False,수납장,...,False,False,미시공,시공불량,False,주방가구공사,타일공사,False,0.95,성공
157,13055537,109,2202,주방발코니,거실발코니,False,벽,미분류,False,PL창,...,True,True,시공불량,시공불량,True,창호공사,창호공사,True,0.95,성공
158,13055554,108,801,주방,주방,True,벽,벽,True,씽크상부장,...,False,False,시공불량,미시공,False,주방가구공사,잡철물공사,False,0.95,성공
159,13055562,106,1204,드레스룸,거실,False,벽,천정,False,화장대,...,False,False,시공불량,시공불량,True,가구공사,코킹공사,False,0.90,성공
160,13055575,108,402,주방,주방,True,벽,바닥,False,씽크상부장,...,False,False,미시공,미시공,True,주방가구공사,마루공사,False,0.90,성공
161,13055585,108,703,주방,공용부,False,벽,벽,True,씽크하부장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
162,13055603,106,1204,주방,거실발코니,False,벽,벽,True,벽지,...,False,False,시공불량,오염,False,도배공사,창호공사,False,0.90,성공
163,13055619,104,401,부부욕실,욕실1,False,벽,천정,False,세면대상판(인조),...,False,False,미시공,시공불량,False,석공사,욕실천정공사,False,0.95,성공
164,13055662,109,2302,현관펜트리,거실,False,벽,바닥,False,펜트리문,...,False,False,시공불량,미시공,False,가구공사,내장공사,False,0.90,성공
165,13055683,103,802,침실2,현관,False,천정,벽,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장목공사,False,0.95,성공
166,13055684,108,501,주방,거실,False,벽,벽,True,수납장,...,False,False,미시공,시공불량,False,주방가구공사,내장공사,False,0.95,성공
167,13055687,108,1304,현관,공용부,False,벽,벽,True,벽지,...,False,False,시공불량,시공불량,True,내장공사,코킹공사,False,0.95,성공
168,13055705,108,1903,실외기,공용부,False,천정,벽,False,도장,...,False,False,흠집,시공불량,False,도장공사,코킹공사,False,0.90,성공
169,13055724,108,803,침실1,거실,False,천정,천정,True,천정지,...,False,False,시공불량,오염,False,도배공사,내장목공사,False,0.90,성공
170,13055732,108,403,침실1,거실,False,벽,벽,True,붙박이장,...,False,False,흠집,시공불량,False,가구공사,코킹공사,False,0.95,성공
171,13055752,108,1903,드레스룸,거실발코니,False,벽,벽,True,화장대상판(인조),...,False,False,흠집,시공불량,False,인조강화석공사,창호공사,False,0.95,성공
172,13055772,108,1304,침실2,현관,False,벽,벽,True,목문,...,False,False,흠집,시공불량,False,목창호공사,목문공사,False,0.90,성공
173,13055817,108,303,거실,거실,True,바닥,벽,False,강마루84,...,False,False,미시공,오염,False,마루공사,도장공사,False,0.90,성공
174,13055826,108,901,주방발코니,거실,False,천정,벽,False,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.90,성공
175,13055831,103,802,안방전면발코니,거실,False,벽,벽,True,도장,...,False,False,시공불량,시공불량,True,도장공사,코킹공사,False,0.80,성공
176,13055833,109,2302,안방,거실,False,벽,벽,True,벽지,...,False,False,시공불량,파손(균열),False,도배공사,미장공사,False,0.90,성공
177,13055837,108,901,주방발코니,욕실,False,벽,벽,True,바탕면(내장),...,False,False,시공불량,미시공,False,내장목공사,전기공사,False,0.95,성공
178,13055839,108,501,침실1,거실,False,벽,벽,True,벽지,...,False,False,시공불량,결로,False,도배공사,도장공사,False,0.90,성공
179,13055855,109,2302,주방,주방,True,벽,바닥,False,씽크상부장,...,False,False,시공불량,파손(균열),False,주방가구공사,엔지니어드스톤공사,False,0.95,성공
180,13055868,108,1304,거실복도,거실,False,벽,천정,False,벽지,...,False,False,시공불량,파손(균열),False,도배공사,도장공사,False,0.90,성공
181,13055891,104,703,주방,공용부,False,벽,천정,False,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,코킹공사,False,0.95,성공
182,13055916,106,1304,주방발코니,거실,False,천정,천정,True,천정면(내장),...,True,True,시공불량,시공불량,True,내장목공사,내장공사,False,0.90,성공
183,13055927,104,501,거실,거실,True,벽,벽,True,준공청소,...,False,False,오염,오염,True,준공청소,코킹공사,False,0.90,성공
184,13055937,104,304,안방,거실발코니,False,벽,벽,True,바탕면(내장),...,False,False,오염,시공불량,False,내장목공사,코킹공사,False,0.90,성공
185,13055947,104,304,안방,현관,False,벽,바닥,False,걸레받이,...,False,False,시공불량,시공불량,True,내장목공사,기타공사,False,0.90,성공
186,13055962,108,1304,부부욕실,부부욕실,True,벽,벽,True,욕실장,...,False,False,미시공,파손(균열),False,욕실가구공사,타일공사,False,0.90,성공
187,13055966,104,304,실외기,공용부,False,바닥,벽,False,에폭시,...,False,False,시공불량,시공불량,True,도장공사,미장공사,False,0.95,성공
188,13056012,108,1001,안방,거실발코니,False,천정,미분류,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,창호공사,False,0.95,성공
189,13056025,108,803,주방,거실,False,벽,벽,True,씽크상부장,...,False,False,시공불량,시공불량,True,주방가구공사,도장공사,False,0.90,성공
190,13056064,109,2402,침실1,거실발코니,False,벽,벽,True,PL창,...,False,False,흠집,시공불량,False,창호공사,코킹공사,False,0.90,성공
191,13056123,104,703,실외기,공용부,False,벽,벽,True,도장,...,True,True,시공불량,파손(균열),False,도장공사,도장공사,True,0.95,성공
192,13056138,108,1001,거실,현관,False,천정,벽,False,천정지,...,False,False,시공불량,시공불량,True,도배공사,내장공사,False,0.95,성공